(function(){
  // -------------------------------------------------------------------
  // ARC XXII — THE CHILD OF FAIR TIDE. Now fully wired, all 24 chapters
  // — Part I ("Something Different"), Part II ("The Veyren Diagnosis"),
  // Part III ("Maera's Diagnostic System"), Part IV ("A Veyren
  // Pregnancy"), and Part V ("The Long Pregnancy"). Gated at
  // arc21Complete + level 330, continuing the established +15-per-arc
  // ladder (XIX:285, XX:300, XXI:315, XXII:330). Ch.24 sets
  // game.arc22Complete = true, matching every other arc's own finale
  // flag.
  //
  // Ch.13-24 (Parts IV-V) were added in a later pass, after Ch.1-12
  // shipped — XP keeps climbing through the twin-sex reveal (Ch.16:
  // 340) and the "years, not months" revelation (Ch.19: 330), the two
  // biggest beats in this back half, with Ch.24's finale bump (380)
  // deliberately kept below Ch.12's twin reveal (400) — same "one
  // centerpiece, not two" convention Arc XX used for its own Ch.20/24
  // split. Ch.23 ("Growing") is the doc's own explicit no-countdown
  // chapter — deliberately the lowest-XP, quietest chapter in this half,
  // matching its "this fades into the background" purpose; nothing here
  // should ever grow into a day-counter.
  //
  // Ch.10 walks through all four stages of Maera's exam as laid out in
  // the design doc (Vital / Life-Resonance / Meridian-Vital-Flow / Womb
  // Resonance) in sequence, on purpose — the doc is explicit that the
  // point is to make this read as a genuine, methodical Veyren medical
  // discipline rather than a single convenient magic-reveal moment.
  //
  // Ch.11 and Ch.12 are deliberately kept as two separate beats, per the
  // doc's own note: the pregnancy confirmation and the twin reveal each
  // get their own reaction from San and Joel rather than being folded
  // into one scene. XP reflects that escalation (320/350/400) — this is
  // the single largest jump in the arc so far, on purpose, since it's
  // the arc's central revelation.
  //
  // Same scope rule as Arc XVII-XXI: this file only wires the story
  // chapters. No pregnancy mechanic, no Maera diagnostic system, no
  // new game.* state beyond the standard comicProgress22 tracking —
  // and per the doc's own note for Ch.23, the pregnancy is meant to
  // have no in-game countdown at all ("no 'Day 180' mechanic"), so
  // nothing here should ever grow into one. Not registered with the
  // objective-chain aggregator; that's still being handled separately.
  //
  // The craving in Ch.1 is written as a specific-but-unnamed sour fruit
  // from the Market Quarter — the doc only says "food she normally
  // wouldn't seek out," so the fruit itself is my invention. Easy to
  // swap for a canon food if there is one.
  //
  // Cover image paths are placeholder guesses following the established
  // convention (ch0N-slugified-title.png) — flagged for confirmation
  // like every chapter image before this, since no art exists yet to
  // confirm the real filenames against.
  // -------------------------------------------------------------------

  const ARC22_CHAPTERS = [
    {id:1, title:'Something I Want', focus:"San develops an unusual craving for food she normally wouldn't seek out. At first it is simply funny — Joel is more amused than concerned and goes out of his way to find what she wants.", image:'assets/comics/arc22/ch01-something-i-want.png', xp:270, action:'🍽️ Follow the Craving'},
    {id:2, title:"You Don't Eat Enough", focus:"Joel notices San has been putting Fair Tide's needs ahead of her own again. He reminds her she's allowed to enjoy her own life — San spent years saving and postponing, Joel carried debts but still enjoyed each day.", image:'assets/comics/arc22/ch02-you-dont-eat-enough.png', xp:280, action:'💬 Let Him Say It'},
    {id:3, title:'Fair Tide Can Wait', focus:"San actually takes Joel's advice, leaving Fair Tide's responsibilities alone for an afternoon to simply enjoy herself with him. She isn't unhappy — she's just forgotten that living is part of the life she's building.", image:'assets/comics/arc22/ch03-fair-tide-can-wait.png', xp:270, action:'☀️ Take the Afternoon'},
    {id:4, title:'Soel Knows Something', focus:"Soel becomes unusually interested in San — following her closely, sleeping near her, and occasionally pressing himself against her abdomen. San assumes he's just being Soel. Neither of them considers pregnancy.", image:'assets/comics/arc22/ch04-soel-knows-something.png', xp:290, action:'🐈 Notice Soel'},
    {id:5, title:'The Sage at the Shrine', focus:"San and Joel encounter the strange Veyren sage. He studies San briefly, and instead of announcing anything, says: \"Some things arrive only when they are ready.\" \"Do not hurry what is growing.\" Then he smiles and disappears.", image:'assets/comics/arc22/ch05-the-sage-at-the-shrine.png', xp:300, action:'🔮 Meet the Sage'},
    {id:6, title:'What Was He Talking About?', focus:"San and Joel try to interpret the sage's words — Fair Tide, the Horizon Engine, some magical phenomenon, even Soel — and eventually dismiss it. Meanwhile, San's unusual cravings continue.", image:'assets/comics/arc22/ch06-what-was-he-talking-about.png', xp:280, action:'🤔 Puzzle It Out'},
    {id:7, title:'The Food Problem', focus:"San's cravings become harder to ignore. Joel has essentially become her unofficial food supplier — the situation stays domestic and funny, but San begins wondering why her appetite has changed so dramatically.", image:'assets/comics/arc22/ch07-the-food-problem.png', xp:280, action:'🍲 Keep Track of It'},
    {id:8, title:'I Feel Fine', focus:"San realizes that despite the strange appetite, she doesn't feel sick — in fact she feels unusually healthy, which makes pregnancy even less likely in her mind. There's no familiar human pattern telling her what's happening.", image:'assets/comics/arc22/ch08-i-feel-fine.png', xp:290, action:'💪 Feel Unusually Healthy'},
    {id:9, title:'Something About Me', focus:"San finally tells Joel something about her body feels different. Rather than going to Jovie or Dr. AA, they decide to seek a Veyren healer who understands Veyren physiology — leading them to Maera Veyr, Veyren Healer & Midwife.", image:'assets/comics/arc22/ch09-something-about-me.png', xp:310, action:'💬 Tell Joel'},
    {id:10, title:"The Healer's Examination", focus:"Maera begins a comprehensive Veyren examination — vital signs, life-resonance, meridian/vital-flow, and a womb resonance reading. San appears healthy by every ordinary measure, but Maera detects a faint second life-signature and sends for her senior midwife.", image:'assets/comics/arc22/ch10-the-healers-examination.png', xp:320, action:'🩺 Begin the Examination'},
    {id:11, title:'The Second Examination', focus:"Maera's senior midwife examines San independently and confirms the pattern. Maera: \"San... I believe you're carrying a child.\" Silence. Neither San nor Joel knows what to say.", image:'assets/comics/arc22/ch11-the-second-examination.png', xp:350, action:'👂 Hear the Second Opinion'},
    {id:12, title:'Two', focus:'Maera detects two distinct developing life signatures, confirmed independently by the midwives. "There are two," she says. Joel: "Two?" Maera: "Two children." San is completely stunned — they\'re having twins.', image:'assets/comics/arc22/ch12-two.png', xp:400, action:'👶👶 Two'},
    {id:13, title:'The Questions Begin', focus:"San and Joel have dozens of questions — how far along she is, when the children will be born, whether they're healthy, what she should eat or avoid. Maera can answer many of them, but not all — the twins' progression doesn't map neatly onto human pregnancy.", image:'assets/comics/arc22/ch13-the-questions-begin.png', xp:290, action:'❓ Ask Everything'},
    {id:14, title:'A Second Kind of Examination', focus:"Maera begins regular monitoring — San's condition, maternal and fetal resonance, magical energy distribution, each twin's growth and movement. Not constant danger-scanning; she's watching the children develop. It becomes an ongoing diagnostic relationship.", image:'assets/comics/arc22/ch14-a-second-kind-of-examination.png', xp:280, action:'🩺 Keep Coming Back'},
    {id:15, title:'Two Different Rhythms', focus:"Maera notices the twins don't share identical resonance patterns — one more physically active, the other with a stronger magical signature. The first hint they'll have distinct personalities. San is fascinated; Joel is obsessed with figuring out which one is the boy.", image:'assets/comics/arc22/ch15-two-different-rhythms.png', xp:290, action:'🎵 Notice the Difference'},
    {id:16, title:'A Son and a Daughter', focus:"Maera's diagnostic system finally establishes the twins are one boy and one girl. Joel is quietly delighted; San becomes unexpectedly emotional about having a daughter. For now they're simply two little lives growing inside her.", image:'assets/comics/arc22/ch16-a-son-and-a-daughter.png', xp:340, action:'👦👧 A Son and a Daughter'},
    {id:17, title:'Nine Months?', focus:"San asks Maera when. Maera doesn't answer immediately — Veyren pregnancies vary considerably. She gives the human-equivalent expectation first, then admits the twins' development isn't following that timetable.", image:'assets/comics/arc22/ch17-nine-months.png', xp:280, action:'📅 Ask "When?"'},
    {id:18, title:'This Is Different', focus:"Maera compares San's progression against her records of previous Veyren pregnancies. The twins are healthy and developing, but slowly — not dangerously, simply slowly. Maera: \"I don't think these children are going to hurry.\"", image:'assets/comics/arc22/ch18-this-is-different.png', xp:290, action:'📊 Compare the Records'},
    {id:19, title:'Years', focus:"Maera has to tell them the pregnancy may take years rather than months — even she can't give an exact duration. Joel processes it calmly: \"Then we'll wait.\"", image:'assets/comics/arc22/ch19-years.png', xp:330, action:'⏳ Hear the Truth'},
    {id:20, title:'Fair Tide Finds Out', focus:"San and Joel tell the Fair Tide community. The reaction is enormous but affectionate — Ate Joy starts planning, the medical staff want to help, and people begin imagining what the settlement will be like with two children growing up there.", image:'assets/comics/arc22/ch20-fair-tide-finds-out.png', xp:300, action:'📣 Tell Everyone'},
    {id:21, title:"Captain's Leave", focus:"San worries pregnancy might interfere with her role as Captain. Joel doesn't tell her what to do — instead they discuss how to keep being themselves while adapting to parenthood. Fair Tide's own infrastructure suddenly has another purpose: it can support a family.", image:'assets/comics/arc22/ch21-captains-leave.png', xp:300, action:'⚓ Talk It Through'},
    {id:22, title:"The Life We Didn't Plan", focus:"San and Joel reflect on their old lives — San saved for a future she believed she'd eventually have time for; Joel never had much money but tried to enjoy what he had. Neither planned this, yet these children are now part of the life they've built.", image:'assets/comics/arc22/ch22-the-life-we-didnt-plan.png', xp:290, action:'💭 Look Back Together'},
    {id:23, title:'Growing', focus:"Time passes. Maera continues monitoring the twins. The children remain healthy, the pregnancy simply continues — no artificial countdown. The story moves into Arc XXIII and beyond while it develops naturally in the background. Soel remains unusually attentive.", image:'assets/comics/arc22/ch23-growing.png', xp:270, action:'🌊 Let It Grow'},
    {id:24, title:"We're Going to Be Parents", focus:"San and Joel stand together at Fair Tide, the harbour they built around them. San rests a hand over her stomach; Joel places his over hers. There are two children, healthy, who may take years to arrive — but they know they'll meet them eventually.", image:'assets/comics/arc22/ch24-were-going-to-be-parents.png', xp:380, action:'🌅 Look Toward It Together'}
  ];
  window.ARC22_CHAPTERS = ARC22_CHAPTERS;

  const ARC22_CHAPTER_SCENES = {
    1: "It starts with a fruit.<br><br>Not one San has ever cared about — a sour, slightly ridiculous thing from a stall at the far end of the Market Quarter that she's walked past a hundred times without a second glance. But this morning she wakes up wanting it with a specificity that's almost embarrassing, and by midday she's thought about little else.<br><br>She says it out loud, half-laughing at herself, and Joel looks up from his breakfast with the expression of a man who has just been handed a mission.<br><br>\"You want fruit,\" he says. \"You. Want fruit.\"<br><br>\"I want that fruit.\"<br><br>He's out the door before she can tell him it isn't that important. He comes back an hour later, triumphant and slightly out of breath, and watches her eat it with more satisfaction than the situation strictly deserves.<br><br>It's funny. That's all it is. Nothing is wrong with her. San doesn't give it another thought.",
    2: "Joel notices it the way he notices most things about her — late, and then all at once.<br><br>Breakfast skipped because a ship needed clearing. Lunch eaten standing up over a ledger. Dinner, if it happens, somewhere between two council matters and a merchant who's very sure his cargo was mislabeled. Fair Tide's needs keep arriving, and San keeps putting them ahead of herself, exactly the way she always has.<br><br>\"You don't eat enough,\" he says, and it isn't really about food.<br><br>San starts to argue, and he waits her out.<br><br>The old world sits between them for a moment, the way it sometimes does. San spent years saving, postponing, telling herself she'd have time to actually live once everything was in order. Joel earned less, carried debts, and still tried to enjoy a little of each day instead of waiting for a perfect future to arrive.<br><br>\"You're allowed to enjoy this,\" he says. \"Your life. Right now, not later.\"<br><br>She doesn't have an argument for that. She's not sure she's ever had one.",
    3: "She actually does it, which surprises them both.<br><br>Fair Tide's responsibilities stay exactly where she leaves them — the ledger closed, the council matters handed off, the harbour trusted to people who've more than earned it. For one afternoon San doesn't fix anything, decide anything, or answer anything.<br><br>They just spend it. Walking, mostly. Eating something that isn't a snack between crises. Sitting somewhere warm with nothing to do and nobody looking for her.<br><br>San isn't unhappy with the life she's built. That's the odd part, realizing it now — she loves it. She'd just forgotten that living is part of what she's building, not something waiting on the far side of it.<br><br>Joel doesn't say I told you so. He just looks pleased, and lets the afternoon be exactly what it is.",
    4: "Soel has always been attentive in the way of cats who've decided a particular person is theirs. This is different, and it takes a few days before either of them names it.<br><br>He follows San more closely now. Sleeps against her side instead of at the foot of the bed. And sometimes, without any obvious reason, he presses himself against her stomach and simply stays there, very still, like he's listening to something.<br><br>San assumes he's just being Soel.<br><br>Joel notices it too, and has no better explanation. They trade a look over the top of the cat, shrug, and let it go.<br><br>Neither of them wonders what he's listening to.",
    5: "They find the shrine by accident, the way people usually find the places that matter — a detour, a wrong turn, a path neither of them planned to take.<br><br>The sage is already there, as if he'd been expecting company. Veyren, unhurried, with the calm of someone who has been watching tides for a very long time. He studies San for a moment. Only a moment. Long enough that she starts to feel looked at in a way she can't quite name.<br><br>He doesn't say what he sees.<br><br>\"Some things arrive only when they are ready,\" he says.<br><br>\"What does that mean?\" San asks.<br><br>\"Do not hurry what is growing.\"<br><br>Joel frowns. \"What's growing?\"<br><br>The sage only smiles. When they look again, the shrine is empty, and there's nobody there at all.",
    6: "They spend most of the walk home trying to work it out.<br><br>Fair Tide, maybe — the settlement itself, still growing. Or the Horizon Engine, some new phase of it nobody's noticed yet. A magical phenomenon of some kind. Something to do with Soel, given how strangely Soel's been behaving lately.<br><br>Each theory sounds plausible for about a minute.<br><br>\"He was probably just being mysterious,\" Joel says finally. \"Sages do that.\"<br><br>\"Probably,\" San agrees, and lets it go.<br><br>The cravings don't. By evening she's thinking about that fruit again, and Joel — without being asked — is already reaching for his coat.",
    7: "It isn't one fruit anymore. It's become a rotating list, each craving arriving with the same sudden, specific certainty as the last, and Joel has, without either of them quite deciding it, become San's unofficial supplier.<br><br>He doesn't complain. If anything he seems to be enjoying it — tracking down whatever she wants with the focus he usually reserves for actual emergencies. It stays domestic. Funny, mostly, the two of them turning grocery errands into something between a game and a small adventure.<br><br>But San catches herself wondering, somewhere between the fourth and fifth unusual request, why any of this is happening at all. Her appetite has never worked like this before.",
    8: "If anything were actually wrong, San reasons, she'd feel it. That's how it's always worked — illness announces itself, one way or another. Fatigue. Nausea. Some unmistakable sense that something's off.<br><br>None of that is here. If anything, she feels better than usual — steady, clear-headed, unusually well for someone whose eating habits have gone this strange. It's the reassurance that keeps her from worrying, and also, without her realizing it, the exact reason she doesn't reach for the obvious explanation.<br><br>Nothing about this fits any pattern she recognizes. So she stops looking for one.",
    9: "She doesn't plan to bring it up. It comes out anyway, quiet, at the end of an ordinary evening, in the tone she uses for things she's been turning over longer than she's admitted.<br><br>\"Something feels different,\" she tells Joel. \"About my body. I don't know if it's anything.\"<br><br>He doesn't dismiss it, and he doesn't panic either. \"Let's get someone to actually look,\" he says.<br><br>Not Jovie, not Dr. AA — competent as they both are, this isn't quite in their wheelhouse. What San's describing doesn't sound like anything human medicine has a name for. It sounds like something that needs someone who actually understands Veyren bodies.<br><br>That's how they end up asking after Maera Veyr — a healer and midwife with decades of experience treating Veyren patients, someone San's heard mentioned in passing more than once but never actually met.",
    10: "Maera doesn't rush into anything, and she doesn't try to sound mystical about it either. She's a healer first — decades of Veyren patients behind her, decades of childbirth attended — and the exam she begins with San is exactly that: an exam, methodical and familiar to her even if none of it is familiar to San.<br><br>She starts with the vital signs. Pulse. Breathing. Temperature. Circulation. General vitality, appetite, sleep. San, by every one of these measures, is remarkably healthy — nothing here suggests illness of any kind, which matches exactly what San's been telling herself for weeks.<br><br>Then Maera moves to something San's never had checked before: her life-resonance. Every living Veyren carries a distinct signature, Maera explains, as familiar to a trained healer as a heartbeat. San should present as one coherent pattern.<br><br>She doesn't.<br><br>There's a second pattern there, faint, woven into San's own. Maera checks again. It doesn't go away.<br><br>Next she traces San's meridians — not hunting for illness this time, but for where San's own vitality is going. And some of it, unmistakably, is being redirected. Given, deliberately, to something else developing inside her.<br><br>This is the point Maera stops treating the exam as routine.<br><br>The last part is the one Veyren midwives have refined over generations without ever needing human instruments — a womb resonance reading, built specifically to detect developing life. Maera performs it once. Then again, to be sure of what she's finding.<br><br>She doesn't say anything yet. She sends for her senior midwife instead.",
    11: "The midwife who arrives has caught more Veyren babies into the world than she could easily count, and she doesn't need Maera's notes to know what she's looking for. She examines San independently, comparing what she finds against decades of her own experience, checking it against pattern after pattern she's encountered before.<br><br>The two of them compare findings quietly, out of San's immediate earshot, in the particular hush of two professionals confirming something neither wants to get wrong.<br><br>Then Maera comes back and sits with San properly.<br><br>\"San,\" she says. \"I believe you're carrying a child.\"<br><br>The room goes very quiet.<br><br>San looks at Joel. Joel looks at San. Neither of them says anything at all for a long moment — not because there's nothing to say, but because there's suddenly too much of it, all at once, with nowhere yet to put any of it.",
    12: "Maera doesn't end the examination there. Something about San's resonance still isn't sitting quite right against a single pregnancy — a shape to it that doesn't match what one developing life should look like.<br><br>She checks again, carefully.<br><br>Two distinct signatures. Not one pattern with an echo. Two, separate, both unmistakably real.<br><br>The midwives confirm it independently, the same way they confirmed everything else — methodically, without assumption, until there's no reasonable way to doubt it.<br><br>\"There are two,\" Maera says finally.<br><br>Joel blinks. \"Two?\"<br><br>\"Two children.\"<br><br>San doesn't manage a response right away. She'd barely had time to absorb one revelation before this one arrived on top of it — not a pregnancy she hadn't expected, but twins she hadn't even had time to imagine.<br><br>Joel reaches for her hand without either of them quite deciding to. Neither of them says anything for a while. There isn't really anything small enough to say.",
    13: "The questions arrive all at once, the way they always do once the shock wears off enough to let curiosity back in.<br><br>How far along is she? When will the children actually arrive? Are they healthy? What should she eat, what should she avoid, what should she stop doing immediately and what was she worried about for nothing?<br><br>Maera answers what she can, patiently, the way San imagines she's answered these same questions a hundred times before for a hundred other frightened, delighted parents. The twins are developing well — that much she's certain of. Healthy, steady, exactly as they should be.<br><br>But some of San's questions get a longer pause before the answer comes, and some don't get a clean answer at all. \"Their progression doesn't line up neatly with what I'd expect,\" Maera admits. \"Not wrongly. Just — differently.\"<br><br>Joel catches San's hand. Neither of them presses her further, not yet. There will be time for the harder questions later. For now, healthy is enough.",
    14: "It becomes a routine faster than San expects — not the anxious, watchful kind she'd half-braced for, but something steadier.<br><br>Maera checks on her regularly now. Her physical condition first, same as always, then the resonance work: San's own signature, each twin's developing pattern, how the shared flow of energy between mother and children is holding. She tracks how each of them is growing, how they move, whether anything about the shared resonance has shifted since the last visit.<br><br>\"You're not checking for something wrong,\" San says, midway through one appointment, watching Maera's expression rather than whatever she's actually sensing.<br><br>\"No,\" Maera agrees. \"I'm watching them grow. That's a different thing entirely.\"<br><br>It settles something in San that she hadn't realized was still unsettled. This isn't crisis management. It's just — care, ongoing, ordinary in its own new way. San starts looking forward to these visits instead of dreading them.",
    15: "\"They're not the same,\" Maera says one afternoon, frowning slightly at whatever she's sensing beneath her hands.<br><br>\"Not the same how?\" San asks.<br><br>\"One of them moves more. The other one — \" Maera pauses, choosing the word carefully. \"Reaches, in a way. Magically. Different rhythms entirely. They're developing as two distinct people already, not two copies of the same thing.\"<br><br>San finds this quietly thrilling in a way she doesn't fully expect. Two lives, not one experience split in half — already different, already themselves, before either of them has even properly arrived.<br><br>Joel finds it thrilling in an entirely more specific way.<br><br>\"So which one's the boy?\" he asks, for what San is fairly sure is the fourth time this week.<br><br>\"I don't know yet, Joel.\"<br><br>\"But if you had to guess—\"<br><br>\"I don't guess,\" Maera says, not unkindly, and San laughs despite herself at the sheer, deflated patience on Joel's face.",
    16: "The answer, when it finally comes, arrives quietly — no fanfare, just Maera setting down what she's holding and looking up at both of them.<br><br>\"One boy,\" she says. \"One girl.\"<br><br>Joel goes very still, then breaks into a grin he doesn't try to hide, delighted in a way that's almost boyish itself. San expects to feel similarly straightforward about it and instead finds herself unexpectedly, foolishly emotional — a daughter, a whole small person who'll be a daughter, and San has no idea yet what that will even mean beyond the sudden fierce ache of wanting to be someone worth having as a mother.<br><br>\"A son and a daughter,\" she repeats, testing how it sounds out loud.<br><br>\"Two entirely separate small disasters,\" Joel offers, and San swats his arm without any real force behind it.<br><br>Neither of them knows yet what these children will become — what they'll look like, what they'll want, who they'll grow into. For now they're simply that: a son, a daughter, two little lives, already distinctly themselves, growing steadily toward whoever they're going to be.",
    17: "It's a simple enough question, San thinks, when she finally asks it outright.<br><br>\"So — when?\"<br><br>Maera doesn't answer right away, which is itself an answer San doesn't love the shape of.<br><br>\"Veyren pregnancies vary,\" she says eventually. \"More than you'd expect, if you're thinking in human terms.\"<br><br>\"Give me something. A range. Anything.\"<br><br>Maera does, at first — a figure that sounds almost reassuringly familiar, close enough to what San remembers from half-forgotten conversations in her old life. San holds onto it for exactly as long as it takes Maera to continue.<br><br>\"That said,\" Maera adds, more carefully now, \"your two aren't tracking against that figure. Not badly. Just — not on it.\"<br><br>\"Meaning?\"<br><br>\"Meaning I'd rather not give you a number I'm not confident in.\" Maera's tone stays gentle, but there's no softening the plain fact underneath it. Something about this pregnancy isn't behaving the way her records say it should.",
    18: "Maera spends longer than usual on this visit, comparing what she's finding against notes San's never actually seen — records going back further than San likes to think about, decades of Veyren pregnancies distilled into whatever shorthand Maera's built for herself over the years.<br><br>\"They're healthy,\" Maera says finally, and San relaxes at that before the rest of the sentence catches up to her. \"They're developing. Just slowly. Slower than anything in my records, honestly — though not dangerously so. Nothing here tells me to worry.\"<br><br>\"But?\"<br><br>\"But I don't think these children are going to hurry,\" Maera says, with something that might almost be a smile. \"Whatever they're doing in there, they're doing it at their own pace.\"<br><br>San sits with that for a moment, and then, unbidden, the sage's voice surfaces in her memory, unplaceable until suddenly it isn't.<br><br>Do not hurry what is growing.<br><br>\"Joel,\" she says slowly. \"I think the sage already knew.\"",
    19: "Maera tells them plainly, because there isn't really a gentle way to say it and she seems to know better than to try dressing it up.<br><br>\"This may take years,\" she says. \"Not months. I can't give you an exact figure — I don't have one to give. I've never attended a pregnancy quite like this before.\"<br><br>San waits for the weight of that to land properly, braced for it, and is almost surprised when it settles into something quieter than panic. Joel takes it more calmly still.<br><br>\"Then we'll wait,\" he says, like it's the simplest thing in the world.<br><br>\"That's it?\" San asks. \"Years, Joel. Years.\"<br><br>\"What else are we going to do?\" He shrugs, and there's nothing careless in it — just the same steadiness he's carried through everything else they've weathered together. \"We've got time. We're not exactly short on it these days.\"<br><br>San finds, somewhat to her own surprise, that she believes him completely.",
    20: "They don't plan some grand announcement. It simply gets out, the way anything does at Fair Tide eventually, and within a day it feels like the entire settlement already knows.<br><br>The reaction is enormous, and entirely affectionate. Ate Joy is already three steps ahead, listing everything San is and isn't allowed to lift, half-serious and entirely unwilling to be argued with. The Medical House staff start rearranging their own plans around \"whenever the Captain needs us,\" without anyone having to ask. Aisyah cries a little and pretends she isn't. Mez makes it about herself within roughly four minutes, which nobody's surprised by.<br><br>More than anything, San notices people starting to imagine it out loud — what Fair Tide will look like with two children actually growing up here, running through the market, underfoot in the Commons, thoroughly unbothered by however strange their arrival turns out to be.<br><br>It stops being San and Joel's private news somewhere in that first afternoon. It becomes Fair Tide's, the way everything important here eventually does.",
    21: "The worry surfaces late one night, quieter than San expects it to be when it finally comes out.<br><br>\"What happens to the Captain part,\" she asks, \"once there's actually two more people who need me?\"<br><br>Joel doesn't hand her an answer. He never does, not for the things that actually matter — he just sits with the question alongside her, turning it over instead of solving it for her.<br><br>\"I don't think it has to be one or the other,\" he says eventually. \"You built a settlement that runs without you standing over every part of it. That wasn't an accident.\"<br><br>San thinks about the Council Hall, the Harbour Office, all of it — every system she and the crew put in place so Fair Tide could stand on its own two feet. She'd built it, she realizes now, without quite admitting to herself why it mattered so much that it work without her.<br><br>\"Fair Tide can hold this too,\" Joel says. \"You made sure of that already. You just didn't know what for yet.\"",
    22: "They end up talking about it properly one quiet evening, the old world surfacing the way it does sometimes, unprompted and a little strange to look back on now.<br><br>\"I spent years saving,\" San says. \"Telling myself I'd actually live once everything was finally in order. I don't think I ever once asked myself when 'in order' was supposed to arrive.\"<br><br>\"I never had much to save,\" Joel says. \"Debts, mostly. But I tried to enjoy what I had while I had it, instead of waiting for some perfect version of things that was always one paycheck away.\"<br><br>\"Neither of us planned this,\" San says, resting a hand over her stomach without quite meaning to.<br><br>\"No,\" Joel agrees. \"We spent our old lives thinking we'd have more time.\"<br><br>\"And now we actually do,\" San finishes, and means it in a way she wouldn't have understood a few years ago — not more time to wait, but more time, simply, to live in. These children weren't part of any plan either of them made. They're part of the life anyway, now, and San finds she wouldn't have it any other way.",
    23: "Time passes the way it does when nobody's counting days against a deadline that doesn't exist.<br><br>Maera keeps checking in, same steady visits as always, and the news stays reassuringly consistent every time: healthy, developing, unhurried. San stops bracing for each appointment the way she used to and starts simply expecting good news, because that's what it's actually been, visit after visit.<br><br>There's no countdown running anywhere in the back of San's mind anymore, no number she's watching tick toward some arbitrary day. There's just this — ordinary life continuing, Fair Tide continuing, the crew's work continuing, and underneath all of it, two small lives taking exactly as long as they need to.<br><br>Soel hasn't let up at all. If anything he's more attentive than ever, curled against San's side most evenings, occasionally pressing close and going very still in that listening way of his. San's stopped questioning it. Whatever he knows, he's not saying — but she trusts him completely to keep saying nothing at exactly the right moments.",
    24: "They end up on the harbour at dusk, the way they seem to end up most important places these days — not because they planned it, just because it's where their feet take them when there's something worth standing still for.<br><br>Fair Tide spreads out behind them, everything they've built from nothing, still growing the way everything here seems to. San rests a hand over her stomach, and Joel covers it with his own without either of them saying anything about it first.<br><br>They know the shape of it now, even without a number attached. Two children. Healthy. Taking their own time, in their own way, arriving whenever they're finally ready and not a moment before. Neither San nor Joel knows exactly what waits on the other side of that — what these two will become, what kind of world they'll grow up into, what kind of parents San and Joel will even turn out to be.<br><br>But they know they'll meet them. Eventually.<br><br>\"We're really going to be parents,\" San says, like she's still testing whether the words hold up out loud.<br><br>\"Yeah,\" Joel says.<br><br>\"Two.\"<br><br>\"Two.\"<br><br>A pause, comfortable rather than heavy.<br><br>\"You wanted a son,\" San says.<br><br>\"You wanted a daughter,\" Joel says.<br><br>San smiles, watching the last of the light settle over the water they've sailed so far to reach.<br><br>\"Apparently Veyren was listening.\""
  };
  window.ARC22_CHAPTER_SCENES = ARC22_CHAPTER_SCENES;

  window.arc22ObjectiveState = function(){
    if (!game.arc21Complete) return null;
    if (level() < 330) return null;
    game.comicProgress22 = game.comicProgress22 || {};
    for (const ch of ARC22_CHAPTERS) {
      if (!game.comicProgress22[ch.id]) return 'complete_arc22_chapter_' + ch.id;
    }
    return 'arc22_part1_complete_for_now';
  };

  window.markArc22ChapterRead = function(id){
    const so = window.arc22ObjectiveState();
    if (so !== ('complete_arc22_chapter_' + id)) return;
    game.comicProgress22 = game.comicProgress22 || {};
    game.comicProgress22[id] = true;
    // Matches every prior arc's own completion flag (arc20/arc21Complete)
    // — self-contained to this file, no aggregator dependency.
    if (id === 24) game.arc22Complete = true;
    const ch = ARC22_CHAPTERS.find(c => c.id === id);
    if (ch) {
      gainXP(ch.xp);
      toast('📖 ' + ch.title + ' — +' + ch.xp + ' Story XP', 3200);
    }
    if (ARC22_CHAPTER_SCENES[id]) {
      game.storyModalQueue = game.storyModalQueue || [];
      game.storyModalQueue.push({ title: ch.title, blurb: ARC22_CHAPTER_SCENES[id] });
    }
    if (typeof saveGameQuiet === 'function') saveGameQuiet();
    if (typeof updateUI === 'function') updateUI();
    if (typeof renderStory === 'function') renderStory();
    if (typeof window.showStoryModal === 'function' && game.storyModalQueue.length) {
      const next = game.storyModalQueue.shift();
      setTimeout(() => window.showStoryModal(next), 400);
    }
  };

  window.__ctShowArc22Splash = function(){
    const overlay = document.getElementById('arc22SplashOverlay');
    if (overlay) overlay.style.display = 'flex';
  };
  window.__ctCloseArc22Splash = function(){
    const overlay = document.getElementById('arc22SplashOverlay');
    if (overlay) overlay.style.display = 'none';
    game.arc22SplashSeen = true;
    if (typeof saveGameQuiet === 'function') saveGameQuiet();
  };

  const oldRenderStoryForArc22 = window.renderStory;
  window.renderStory = function(){
    if (oldRenderStoryForArc22) oldRenderStoryForArc22();
    const container = document.getElementById('storyContent');
    if (!container) return;
    const arc22Ready = window.arc22ObjectiveState() !== null;
    if (arc22Ready && !game.arc22SplashSeen && typeof window.__ctShowArc22Splash === 'function') {
      window.__ctShowArc22Splash();
    }
    let html = '<section class="story-act story-quest-panel"><div class="story-act-header">'+
      '<img src="assets/comics/arc22/arc22-cover-the-child-of-fair-tide.png" alt="Arc XXII — The Child of Fair Tide" style="width:100%;border-radius:8px;margin-bottom:12px;">'+
      '<div class="story-act-kicker">Arc XXII</div><div class="story-act-title">The Child of Fair Tide</div>'+
      '<div class="story-act-tagline">Something new is growing.</div></div>';
    if (!arc22Ready) {
      html += '<div class="story-chapter locked"><div class="story-chapter-title">🔒 Arc XXII Locked</div><div class="story-chapter-sub">'+
        (!game.arc21Complete ? 'Finish Arc XXI first.' : 'Reach Level 330 to begin.')+'</div></div></section>';
      container.insertAdjacentHTML('beforeend', html);
      return;
    }
    const so = window.arc22ObjectiveState();
    ARC22_CHAPTERS.forEach(function(ch){
      const done = !!(game.comicProgress22 && game.comicProgress22[ch.id]);
      const ready = !done && so===('complete_arc22_chapter_'+ch.id);
      const status = done?'✓ COMPLETE':(ready?'CURRENT':'🔒 LOCKED');
      let action;
      if (ready) {
        action = 
          '<button class="btn btn-small btn-success" onclick="markArc22ChapterRead('+ch.id+')">'+esc(ch.action || '✓ Mark Chapter Read')+'</button>';
      } else action = '<div class="story-chip">Follow the current Objective.</div>';
      html += '<article class="quest-item '+(done?'completed':(ready?'active':''))+'"><strong>Chapter '+ch.id+' — '+esc(ch.title)+'</strong><br>'+
        '<span style="font-size:.82rem;opacity:.82;">'+esc(ch.focus)+'</span><br>'+
        '<span style="font-size:.78rem;">'+status+'</span> <span style="font-size:.76rem;opacity:.75;">📖 Story XP: +'+ch.xp+'</span><div class="story-actions">'+action+'</div></article>';
    });
    if (so==='arc22_part1_complete_for_now'){
      html += '<div class="story-chapter" style="margin-top:8px;"><div class="story-chapter-sub">✓ All available Arc XXII chapters read so far. More chapters are on the way — check back soon.</div></div>';
    }
    html += '</section>';
    container.insertAdjacentHTML('beforeend', html);
  };
})();
