(function(){
  // -------------------------------------------------------------------
  // ARC XXIII — THE WIDER TIDE. Gated at arc22Complete + level 345,
  // continuing the established +15-per-arc ladder (XX:300, XXI:315,
  // XXII:330, XXIII:345). Ch.24 sets game.arc23Complete = true, matching
  // every other arc's own finale flag.
  //
  // Core theme, per the outline this arc was built from: "A home
  // becomes important when people beyond its walls begin to depend on
  // it." Unlike Arc XXI, this isn't a construction arc — every building
  // Fair Tide has already stands. Arc XXIII is about what happens once
  // people actually start using them: more traffic, more requests, more
  // strangers choosing Fair Tide on purpose rather than passing through
  // it by accident. Deliberately doesn't dwell on San's pregnancy (Arc
  // XXII's own thread keeps developing quietly in the background,
  // per that arc's explicit "no countdown" note) — this arc's job is to
  // widen the world around San and Joel, not narrow back onto them.
  //
  // Same scope rule as every arc file since XVII: this file only wires
  // the story chapters. The mechanics Ch.1-18's own gameplay notes call
  // for (port traffic, market activity, cargo storage, trade agreements,
  // neutral harbour events, warden assignments, harbour defence, and two
  // new council policies) live in the separate scripts/arc23-mechanics.js,
  // same split used for Arc XXII's Maera mechanics.
  //
  // Ch.19 (The Night Market) is written as a proper San/Joel domestic
  // beat — deliberately light and a little silly, per the outline's own
  // note that the arc shouldn't be "about romance," just keep the
  // relationship thread visibly alive alongside everything else growing
  // around it.
  //
  // Ch.21-24 (Part V, "Something Watches") plant the first Nameless
  // foreshadowing on purpose: nothing overt, no antagonist named, no
  // confrontation — just the quiet, deliberate unease of Fair Tide's
  // reputation reaching further than San can currently see or control.
  // XP escalates toward Ch.17 ("Ships Come and Go," the montage payoff
  // to "Fair Tide Can Stand Alone" and this arc's actual centerpiece) at
  // 400, with Ch.24's finale bump (380) kept below it — the same "one
  // centerpiece, not two" convention used for Arc XX's Ch.20/24 split and
  // Arc XXII's Ch.12/24 split.
  //
  // Cover image paths are placeholder guesses following the established
  // convention (chNN-slugified-title.png) — flagged for confirmation
  // like every chapter image before this, since no art exists yet to
  // confirm the real filenames against.
  // -------------------------------------------------------------------

  const ARC23_CHAPTERS = [
    {id:1, title:'More Ships Than Before', focus:"San notices Fair Tide is receiving substantially more traffic — merchant vessels, independent captains, and travelers choosing it deliberately rather than simply stopping because it's convenient. The Harbour Office and Market Quarter start getting genuinely busy.", image:'assets/comics/arc23/ch01-more-ships-than-before.png', xp:260, action:'⚓ Watch the Harbour'},
    {id:2, title:'Everyone Wants Something', focus:"Growth means requests — supplies, repairs, storage, safe harbour, trade, information, route access, protection. San tries to handle too much of it personally, until Joel points out she built all those offices so she wouldn't have to.", image:'assets/comics/arc23/ch02-everyone-wants-something.png', xp:270, action:'📋 Let the Offices Work'},
    {id:3, title:'The Market Has Its Own Life', focus:"The Market Quarter gets busy enough that San realizes she doesn't need to dictate every transaction. Merchants start negotiating among themselves; prices and availability begin shifting on their own with incoming ships and recent voyages.", image:'assets/comics/arc23/ch03-the-market-has-its-own-life.png', xp:270, action:'🛍️ Let the Market Breathe'},
    {id:4, title:'The Captain Who Came Back', focus:"An independent captain who visited Fair Tide once returns specifically because that first experience was good. San realizes people are choosing Fair Tide because they trust it — not because she's famous, not because the Crimson Tide is powerful, but because the port works.", image:'assets/comics/arc23/ch04-the-captain-who-came-back.png', xp:280, action:'⚓ Welcome Them Back'},
    {id:5, title:'A Place to Leave Things', focus:"Storage becomes unexpectedly important — ships want to leave cargo at Fair Tide while traveling elsewhere. The Supply House and Harbour Office have to work out proper procedure, and Fair Tide starts feeling like a genuine trade hub rather than a place people merely pass through.", image:'assets/comics/arc23/ch05-a-place-to-leave-things.png', xp:280, action:'📦 Set the Procedure'},
    {id:6, title:'No Captain Owns This Place', focus:"A visiting captain assumes Fair Tide is effectively San's personal territory. San corrects them — Fair Tide belongs to the community. She's its founder and its leader, but she isn't trying to become its ruler.", image:'assets/comics/arc23/ch06-no-captain-owns-this-place.png', xp:270, action:"🗣️ Set It Straight"},
    {id:7, title:'The Neutral Table', focus:"Several captains with competing interests arrive at Fair Tide, willing to sit at the same table only because Fair Tide is neutral ground. San doesn't solve their disagreement for them — she simply provides the place where they can work it out themselves.", image:'assets/comics/arc23/ch07-the-neutral-table.png', xp:280, action:'🪑 Offer the Table'},
    {id:8, title:'The First Fair Tide Agreement', focus:"A merchant group proposes a recurring trade arrangement. San has to decide, for the first time, what Fair Tide will formally provide and what it expects in return — the first real step toward structured trade relationships.", image:'assets/comics/arc23/ch08-the-first-fair-tide-agreement.png', xp:300, action:'🤝 Strike the Agreement'},
    {id:9, title:"Caelan's Work", focus:"As Fair Tide's infrastructure gets busier, Caelan becomes increasingly essential — magical equipment, repairs, defensive systems. Ate Joy protects people; Caelan keeps the things protecting people actually working. He's becoming Fair Tide's infrastructure specialist, not just \"the engineer.\"", image:'assets/comics/arc23/ch09-caelans-work.png', xp:280, action:'🔧 Watch Caelan Work'},
    {id:10, title:"The Warden's Watch", focus:"Ate Joy notices that more visitors means more opportunities for trouble. Not paranoid about it — practical. She sets up a real system for keeping Fair Tide safe, assigning attention to the harbour, the market, the warehouses, the residential quarter, and the buildings that matter most.", image:'assets/comics/arc23/ch10-the-wardens-watch.png', xp:290, action:'🛡️ Set the Watch'},
    {id:11, title:"A Merchant's Problem", focus:"A merchant loses part of a shipment. Fair Tide helps resolve it — and, importantly, San doesn't simply cover the loss out of her own pocket the way she once might have. The settlement itself now has systems built for exactly this kind of problem.", image:'assets/comics/arc23/ch11-a-merchants-problem.png', xp:280, action:'🤝 Help Resolve It'},
    {id:12, title:'The Harbour Office', focus:"The Harbour Office becomes one of the busiest buildings in Fair Tide — registration, docking, cargo handling, departure records, route information, all of it now genuinely necessary rather than a formality nobody used.", image:'assets/comics/arc23/ch12-the-harbour-office.png', xp:290, action:'⚓ Handle the Office'},
    {id:13, title:'The Routes Are Becoming Crowded', focus:"The Route Observatory shows something unexpected: several routes are becoming increasingly active. Fair Tide is becoming part of a network — the first hint that the port's importance extends well beyond Veyren itself.", image:'assets/comics/arc23/ch13-the-routes-are-becoming-crowded.png', xp:300, action:'🔭 Read the Routes'},
    {id:14, title:'A Request From Elsewhere', focus:"Fair Tide receives a request from a settlement San has never personally visited. They heard about Fair Tide through other travelers. That's the turning point — Fair Tide's reputation now travels farther than the Crimson Tide itself does.", image:'assets/comics/arc23/ch14-a-request-from-elsewhere.png', xp:290, action:'📜 Take the Request'},
    {id:15, title:'The People Who Stay', focus:"Some travelers begin staying at Fair Tide for extended periods — not everyone wants to sail constantly. Some want work, safety, trade, community, or simply somewhere to start over. San realizes Fair Tide is attracting people who were never part of the original crew.", image:'assets/comics/arc23/ch15-the-people-who-stay.png', xp:300, action:'🏘️ Welcome Them'},
    {id:16, title:'A Port Needs Rules', focus:"The Council Hall becomes important in a new way — the community needs practical rules for docking, commerce, disputes, storage, security, visitors, resource use. San doesn't want arbitrary rules. She wants rules people can actually understand.", image:'assets/comics/arc23/ch16-a-port-needs-rules.png', xp:310, action:'📜 Set the Rules'},
    {id:17, title:'Ships Come and Go', focus:"A quiet, montage-like stretch of Fair Tide functioning without San personally overseeing every piece of it. Ships arrive, cargo moves, people work, children play, the market opens, the Warden patrols, the Workshop hums along — and San simply watches from a distance. The payoff to \"Fair Tide Can Stand Alone.\"", image:'assets/comics/arc23/ch17-ships-come-and-go.png', xp:400, action:'🌅 Watch It Run'},
    {id:18, title:"Brada's Ballista", focus:"Brada notices that Fair Tide's growing traffic also makes it a more attractive target, and begins developing the harbour's defensive artillery. Not because Fair Tide is under attack — because it's worth preparing for, now that it's worth defending at all.", image:'assets/comics/arc23/ch18-bradas-ballista.png', xp:300, action:'🔫 Build the Defence'},
    {id:19, title:'The Night Market', focus:"A proper Fair Tide night market becomes an event — and a San/Joel evening out. They walk through it, eat too much, argue about buying something neither of them needs. Joel wins one argument. San wins another. Neither of them remembers what the original argument was about.", image:'assets/comics/arc23/ch19-the-night-market.png', xp:300, action:'🌙 Walk the Night Market'},
    {id:20, title:'A Wider Family', focus:"Ate Joy becomes increasingly woven into Fair Tide's community — no longer simply Joel's sister. People come to her for help. Children know her by name. Workers trust her without being told to. She's becoming one of the settlement's own recognizable protectors.", image:'assets/comics/arc23/ch20-a-wider-family.png', xp:290, action:'🛡️ See Her Place'},
    {id:21, title:'The Quiet Visitor', focus:"Someone arrives who doesn't behave like an ordinary merchant. They ask unusual questions — nothing overtly threatening, but pointed: about routes, the Horizon Chamber, San's authority, Fair Tide's independence, who actually controls access to the harbour. San notices. She doesn't know why it bothers her.", image:'assets/comics/arc23/ch21-the-quiet-visitor.png', xp:300, action:'👀 Notice Them'},
    {id:22, title:'Who Told You About Us?', focus:"Another visitor mentions something they shouldn't reasonably know. San starts asking who told them about Fair Tide. The answer is ordinary — might even be true — but San begins realizing information about Fair Tide is spreading through channels she doesn't control.", image:'assets/comics/arc23/ch22-who-told-you-about-us.png', xp:310, action:'❓ Ask the Question'},
    {id:23, title:'The Harbour Everyone Knows', focus:"San and Joel talk through what Fair Tide has actually become — no longer their little port, but a place with merchants, workers, families, captains, travelers, agreements, responsibilities, and people who genuinely depend on it. Joel: \"You wanted somewhere people could belong.\" San: \"I didn't expect this many people.\"", image:'assets/comics/arc23/ch23-the-harbour-everyone-knows.png', xp:320, action:'💬 Talk It Through'},
    {id:24, title:'The Wider Tide', focus:"The arc closes with Fair Tide bustling beneath the evening sky, ships from different places sitting in the harbour, the Crimson Tide preparing for another departure. San understands, finally, that Fair Tide isn't growing because the Crimson Tide carries it — the Crimson Tide is becoming one part of something much larger. And far away, someone is watching the routes. Not attacking. Not interfering. Just watching.", image:'assets/comics/arc23/ch24-the-wider-tide.png', xp:380, action:'🌊 Look at the Wider Tide'}
  ];
  window.ARC23_CHAPTERS = ARC23_CHAPTERS;

  const ARC23_CHAPTER_SCENES = {
    1: "San notices it the way she notices most changes at Fair Tide now — not all at once, but in the accumulation of small, ordinary things that stop being ordinary once she actually adds them up.<br><br>More sails on the horizon most mornings. The Harbour Office's ledger filling a page faster than it used to. A line at the Market Quarter that wasn't there a season ago. None of it is dramatic. All of it is new.<br><br>\"We're getting busier,\" she says to Joel, mostly to herself.<br><br>\"You built a port,\" he says. \"Ports get busy.\"<br><br>\"I know. I just didn't expect it to actually happen this fast.\"<br><br>She stands at the Harbour Office window for a while, watching yet another unfamiliar hull come in to dock, and lets herself feel, for a moment, something she doesn't let herself feel often enough: that the thing she built is working.",
    2: "The requests start arriving faster than San can personally keep track of — supplies here, a repair there, someone wanting safe storage, someone else wanting information about a route nobody's charted yet. Trade proposals. Protection asked for by people who've never sailed with the Crimson Tide and never will.<br><br>San tries to handle all of it herself, the way she's always handled everything, and by the third day she's exhausted and behind on half of it anyway.<br><br>Joel finds her buried in paperwork that isn't strictly hers to be buried in.<br><br>\"You built all those offices,\" he says, \"so you wouldn't have to do everything yourself.\"<br><br>She wants to argue. She doesn't have the energy to.<br><br>\"Let the Harbour Office handle the harbour requests,\" he continues. \"Let the Council handle the disputes. You don't have to be the answer to every question that walks through the gate anymore.\"<br><br>It takes her the rest of the week to actually believe him. It takes about a day, once she does, to notice how much lighter everything feels.",
    3: "San walks through the Market Quarter expecting, out of habit, to be asked to settle something — a price dispute, a stall placement, some small friction that used to need her word to resolve.<br><br>Nobody asks her anything.<br><br>Two merchants are already negotiating a supply trade between themselves, loud and animated and entirely uninterested in San's opinion. A price has shifted since last week, apparently, because three more ships came through and undercut somebody's monopoly on dried fish. Nobody consults San about any of it. The market is simply doing what markets do, on its own, without her standing in the middle of it.<br><br>She finds this strangely moving. Not because she's not needed — because she built something that doesn't need her standing in the middle of it to function. That was always the point. She just hadn't actually watched it happen before.",
    4: "The captain who returns is someone San barely remembers — one docking, months back, unremarkable at the time. He remembers Fair Tide with a specificity that catches her off guard.<br><br>\"Fair harbour fees, straight answers, nobody tried to shake me down for a berth,\" he says, tying off his own lines without waiting to be told where. \"I've sailed a lot of ports. Most of them aren't worth a second stop.\"<br><br>\"And this one is?\"<br><br>\"This one's worth coming back to on purpose.\"<br><br>San turns the sentence over for the rest of the day. It sits differently than she expects. People aren't choosing Fair Tide because of who she is or what the Crimson Tide's done. They're choosing it because the port itself, plainly and repeatedly, works. That's a different kind of reputation than the one she's used to carrying — quieter, and somehow more solid for it.",
    5: "The first ship that asks to leave cargo behind catches the Harbour Office completely unprepared. There's nowhere designated for it, no procedure for who's responsible if something goes missing, no clear answer for how long is too long to leave something sitting in someone else's warehouse.<br><br>San and the Supply House work it out together over an afternoon that involves more arguing about liability than she expected — who signs for what, what gets logged, what happens if a ship never comes back for its goods at all.<br><br>By evening there's an actual system: a ledger, a fee, a clear point of contact. Small, unglamorous, entirely necessary.<br><br>It's not romantic work. But watching the first properly-logged deposit get filed away, San recognizes the feeling underneath it — this is what a real trade hub looks like from the inside. Not grand gestures. Just somewhere people can trust to hold onto something and give it back.",
    6: "The captain says it almost carelessly, the way people say things they've never had to question before.<br><br>\"Your port, your rules, I imagine.\"<br><br>\"It's not my port,\" San says, more sharply than she means to. \"It's Fair Tide's.\"<br><br>He blinks, clearly expecting a different answer.<br><br>\"I run the Crimson Tide,\" she continues, quieter now. \"I lead the council here. But this isn't mine to hand out favors from or shut down on a whim. It belongs to everyone who's built a life here — the ones working the harbour, the ones running the market, the ones who never sailed with me at all and have exactly as much stake in this place as I do.\"<br><br>The captain looks at her for a long moment, recalculating something.<br><br>\"Understood,\" he says, and means it a little more carefully than before.<br><br>San doesn't dwell on it, but it matters to her more than she says out loud — that being the founder was never supposed to mean being the ruler.",
    7: "Three captains arrive within a day of each other, and it becomes obvious almost immediately that at least two of them would rather not be in the same harbour, let alone the same room.<br><br>They come anyway. That's the part San notices — whatever's between them, all three are willing to sit down together specifically because it's Fair Tide, specifically because nobody here has a stake in whichever side wins.<br><br>San sets them up at a table in the Council Hall, provides tea nobody drinks, and says almost nothing for the entire negotiation. It isn't her disagreement to solve. It was never supposed to be.<br><br>They argue for two hours. They leave with something resembling an agreement, shake hands they clearly don't fully mean, and sail out within the day.<br><br>San doesn't know exactly what they settled. She isn't sure it matters. What matters is that they needed neutral ground to settle it on, and Fair Tide was the only place that qualified.",
    8: "The merchant group's proposal is more formal than anything San's dealt with before — a standing arrangement, not a one-time trade. Regular deliveries in exchange for guaranteed dock priority and a fixed rate. Numbers on paper, expectations spelled out on both sides, something meant to outlast any single transaction.<br><br>San reads it twice before she lets herself sign anything.<br><br>\"This isn't a favor,\" she says slowly, working it out as she talks. \"This is Fair Tide actually promising something, to people who aren't us.\"<br><br>\"That's usually what an agreement is,\" the merchant says, not unkindly.<br><br>She signs it anyway, because it's a fair deal and because refusing it out of caution alone isn't leadership, it's just fear wearing leadership's clothes. But she signs it slowly, aware that this is a door she hasn't opened before — Fair Tide making commitments that will still be owed long after this particular ship has sailed on.",
    9: "The Workshop doesn't stop humming these days, and most of that is Caelan.<br><br>Defensive wards recalibrated after every new arrival strains them slightly differently. A merchant's cargo-hold enchantment gone slightly wrong, fixed before the owner even notices it was broken. The Harbour Office's own equipment, kept running through sheer stubborn attention nobody asked him to give it.<br><br>\"Ate Joy keeps people safe,\" San says, watching him work. \"What do you do?\"<br><br>Caelan doesn't look up from what he's doing. \"I keep the things keeping people safe actually working.\"<br><br>It's a small distinction and San finds she likes it a great deal. He isn't simply the engineer anymore, the person you send for when something breaks. He's become the reason half of Fair Tide's infrastructure keeps working at all, quietly, without anyone but San seeming to notice how much of it runs through him.",
    10: "Joy doesn't announce any of this with alarm. That's not her style, and San's grateful for it — the last thing Fair Tide needs is its own Warden treating every new face like a threat.<br><br>Instead she lays it out practically, the way she lays out everything. More visitors means more opportunities for something to go wrong, simple as that, and \"everyone handling their own corner of it separately\" doesn't scale the way it used to when Fair Tide was smaller.<br><br>So she builds a real system — attention on the harbour when ships come in, someone watching the market during the busiest hours, the warehouses checked on a rotation instead of whenever somebody remembers, the residential quarter looked after the way a neighborhood looks after itself, the buildings that actually matter most given the closest watch of all.<br><br>San watches her lay it all out on a map, methodical and entirely unbothered, and feels the particular relief of watching someone competent take a real problem and simply solve it.",
    11: "The merchant is more embarrassed than angry when he reports it — part of his shipment simply isn't there, lost somewhere between the ship and the warehouse, and he doesn't know whose fault it is any more than San does.<br><br>The old version of this, San thinks, would have ended with her personally covering the loss out of guilt and goodwill, and everyone quietly understanding that Fair Tide's fairness ran exactly as deep as San's own pocket.<br><br>It doesn't happen that way this time. The Harbour Office pulls its own records. The Supply House checks its own log. Between the two of them they work out where the shipment actually went missing — a mislabeled crate, nobody's fault exactly, easily enough resolved with what's actually on hand.<br><br>San watches the whole thing get sorted without writing a single gold piece out of her own funds, and recognizes it for what it is: not her generosity holding this place together anymore. Its own systems, actually working.",
    12: "The Harbour Office used to have slow days. San remembers them fondly, in the particular way people remember things right before those things stop existing.<br><br>There aren't slow days anymore. Registration for new arrivals, docking assignments juggled around each other, cargo logged in and out, departure records kept properly instead of scrawled onto whatever paper was nearest, route information requested by captains who've genuinely never sailed these waters before.<br><br>San spends an afternoon just watching it function — watching the staff who work there handle a rhythm she barely recognizes from when this building first went up. It isn't glamorous work. It's the unglamorous work that makes everything else here possible, and San makes a point of telling them exactly that before she leaves.",
    13: "The Route Observatory has always been quiet work — logging, cross-referencing, slow accumulation of what's actually known about the worlds Fair Tide touches. San doesn't expect it to show her anything alarming.<br><br>It doesn't, exactly. What it shows her is stranger than alarming.<br><br>Several routes that used to sit mostly unused are seeing real traffic now — not just Fair Tide's own ships, but others, cutting through waters that only make sense to cut through if you're heading somewhere near Fair Tide itself.<br><br>\"We're not just a stop on someone's existing route anymore,\" she says slowly, tracing the pattern with a finger. \"We're becoming part of the route.\"<br><br>It's a bigger thought than she expects it to be, standing there in a room built for careful measurement. Fair Tide isn't simply growing. It's becoming a fixed point other people's plans are starting to be built around.",
    14: "The request arrives through an ordinary channel — a traveling captain relaying a message on someone else's behalf — from a settlement whose name San doesn't recognize at all.<br><br>\"They've never sent anyone here,\" she says, reading it twice. \"I've never been there. I don't think anyone from the crew has.\"<br><br>\"Then how do they know to ask?\" Joel asks.<br><br>That's the actual question, and San doesn't have a tidy answer for it. Somewhere along the line, someone who passed through Fair Tide told someone else, who told someone else again, until a settlement she's never set foot in decided Fair Tide was worth asking something of.<br><br>It's a strange kind of pride, realizing this. The Crimson Tide can only be in one place at a time. Fair Tide's name, apparently, can be almost anywhere.",
    15: "It starts with one traveler who simply doesn't leave when San expects them to.<br><br>Then another. Then a small handful, each with their own reason — tired of constant sailing, looking for steady work instead of the next voyage, wanting somewhere safe to be for once instead of somewhere safe to pass through. A couple of them, San learns almost by accident, are starting over from something they don't talk about much.<br><br>None of them signed on with the Crimson Tide. None of them are crew, in any sense San's used to thinking about the word. They're just — staying. Building something small and ordinary here because Fair Tide, unlike wherever they came from, seems to let them.<br><br>San finds herself genuinely moved by it, more than she expects. She built this place thinking about her own crew's future. She didn't quite anticipate it becoming other people's future too.",
    16: "The Council Hall fills up differently these days — fewer disputes between people San already knows, more genuinely new questions from people who've never had to ask them before. What happens if two ships want the same berth. What counts as fair use of shared storage. Who's responsible if a newcomer causes trouble nobody warned them about.<br><br>San resists the urge to write down a hundred rules for a hundred possible situations. That's not what anyone here actually needs.<br><br>\"Simple rules,\" she says, to the Council and mostly to herself. \"Ones people can actually remember without a lawyer. Docking. Trade. What happens when there's a dispute. What Fair Tide expects from visitors, and what visitors can expect from Fair Tide.\"<br><br>It takes longer than she expects to get it right — plain enough to be useful, fair enough that nobody feels singled out. But by the end of it, Fair Tide has something it never quite had before: rules that exist because people needed them, not rules that exist because someone thought a port ought to have some.",
    17: "San spends an entire afternoon doing nothing at all, which is itself the point.<br><br>She watches from the Harbour Office balcony as an unfamiliar ship docks itself without anyone needing to explain the process. Cargo moves from hold to warehouse along a route the dockworkers have clearly walked a hundred times without her ever watching them do it. A child chases another child past the Market Quarter, weaving between stalls that are conducting their own business entirely without her. Joy walks her rounds in the distance, unhurried, exactly where she's supposed to be. Somewhere behind her, the Workshop is making the particular clattering noise that means Caelan is fixing something nobody asked him to fix yet.<br><br>Nobody looks up at her. Nobody needs to. Fair Tide simply continues, the way a living thing continues, whether or not anyone is standing over it making sure it remembers how.<br><br>San built this. She keeps having to remind herself of that, watching it run without her hand anywhere on it. This was always the actual goal — not a port that needs her, but a home that doesn't have to.",
    18: "Brada doesn't frame it as an emergency, which is exactly why San takes it seriously.<br><br>\"Nobody's coming for us,\" he says. \"Not that I know of. But we're worth something now, and worth something is exactly the kind of place that eventually attracts trouble it didn't ask for.\"<br><br>He's already sketched out what he wants — proper defensive artillery along the harbour approach, something with real range, something that doesn't depend on Joy's people being in exactly the right spot at exactly the right moment. Practical. Unhurried. The opposite of panic.<br><br>San approves the plans without much argument. It isn't the Fair Tide of a season ago, small enough that nobody would bother attacking it. It's a place other people have started depending on, which means it's also become a place worth protecting properly, before anyone ever actually needs it to be.",
    19: "The night market is Fair Tide's own idea, born out of nothing more complicated than lanterns, good weather, and enough stalls willing to stay open past dark to make it worth doing properly. San and Joel go because everyone else seems to be going, and because neither of them has had an actual evening out in longer than either wants to admit.<br><br>They eat too much. They argue, with real conviction and zero actual stakes, over whether a particular carved trinket is worth the asking price — San insists it's overpriced nonsense, Joel insists it's exactly the kind of nonsense worth having, and somehow he wins that argument by simply buying it before she can stop him.<br><br>She wins the next one, whatever it was, ten minutes later, with equal conviction and equally little memory of what it was actually about.<br><br>By the time they walk home, lantern-lit and pleasantly full, neither of them could reconstruct the argument if their lives depended on it. It doesn't matter. It was a good night, uncomplicated in a way their lives rarely get to be, and that's the entire point of it.",
    20: "Joy's become someone Fair Tide reaches for without thinking about it first.<br><br>A worker comes to her with a problem that isn't strictly a Warden's business, because she's simply become the person people bring things to. A child, lost for ten frightened minutes near the Supply House, is delivered straight to her instead of to San, because the child already knew exactly who to look for. Someone new to Fair Tide asks, without hesitation, \"who do I talk to about this,\" and gets Joy's name before anyone's even finished the sentence.<br><br>San watches this happen more and more and realizes something she hadn't quite named before: Joy isn't just Joel's sister who happens to guard the place anymore. She's become one of Fair Tide's own fixed points — trusted the way San is trusted, known the way San is known, for reasons that have nothing to do with being anyone's sister or anyone's captain.",
    21: "The visitor doesn't do anything San can point to afterward as actually suspicious. That's what unsettles her about it.<br><br>Ordinary clothes. An ordinary reason for being at Fair Tide, on the surface. But the questions are never quite where a merchant's questions usually land — not prices, not cargo, not trade routes in the way a trader asks about trade routes. Instead: how the Horizon Chamber works. Who exactly has the final say over harbour access. Whether San's authority here is formal or just assumed. How independent Fair Tide actually is, and from whom.<br><br>Nothing about any single question is alarming on its own. Together, laid end to end, they add up to something San can't quite name yet, and can't quite shake either.<br><br>She doesn't say anything to the visitor. She just remembers the questions, longer than she means to.",
    22: "It's a small thing, almost nothing — a second visitor mentions, in passing, something about the Horizon Chamber that San is fairly certain was never public knowledge.<br><br>\"Where did you hear that?\" she asks, keeping her voice light.<br><br>The answer is ordinary. Plausible, even — a name she half-recognizes, a conversation that could easily have happened exactly the way it's described. It might be entirely true.<br><br>But San finds herself asking the same question of the next few strangers who mention something they shouldn't quite know, and getting a similar shape of answer each time — reasonable, untraceable, impossible to actually disprove.<br><br>Somewhere information about Fair Tide is moving through channels San has no visibility into at all. She doesn't know who's listening, or why, or what they intend to do with what they hear. She just knows, now, that it's happening.",
    23: "They end up talking about it properly that evening, the two of them alone with the noise of the settlement still audible somewhere beyond the walls.<br><br>\"It isn't ours anymore,\" San says finally. \"Not the way it used to be. Not just our little port.\"<br><br>\"No,\" Joel agrees. \"It's got merchants now. Workers. Families. Captains who come back on purpose. People who've never even met you, depending on something you built.\"<br><br>\"I didn't expect this many people,\" San admits.<br><br>Joel looks at her for a moment, something gentle and a little amused in it.<br><br>\"You wanted somewhere people could belong,\" he says. \"That's usually how homes work. They don't stay small just because you built them small.\"<br><br>San doesn't have an answer for that right away. She just sits with it — the strange, outsized weight of having built something that grew past the shape she originally imagined for it, and the stranger comfort of realizing that was always going to be the actual measure of whether it worked.",
    24: "The harbour is busy even at dusk, which still isn't something San's fully used to. Ships from places she's never charted sit at anchor alongside her own. Lanterns go up along the Market Quarter as the light fails. Somewhere behind her, the Crimson Tide is being readied for another departure, same as always, except that it doesn't feel like the center of anything anymore — just one ship among several, in a harbour that's stopped needing it to be the reason any of this exists.<br><br>San stands at the edge of the dock and lets herself actually see it, all at once, the way she rarely lets herself see anything all at once.<br><br>The Crimson Tide didn't build this by carrying it. Fair Tide simply grew, the way things grow when enough people decide to put something of themselves into the same piece of ground — and now the Crimson Tide is just one part of something considerably larger than the ship that started it.<br><br>Far off, past the edge of what San can actually see, someone is watching the routes that lead here. Not attacking. Not interfering. Just watching, patient in a way that doesn't feel accidental.<br><br>San doesn't know that yet. She just feels, standing there in the last of the light, that Fair Tide has become something the wider world has finally started to notice — and that noticing, once it starts, rarely stays quiet for long."
  };
  window.ARC23_CHAPTER_SCENES = ARC23_CHAPTER_SCENES;

  window.arc23ObjectiveState = function(){
    if (!game.arc22Complete) return null;
    if (level() < 345) return null;
    game.comicProgress23 = game.comicProgress23 || {};
    for (const ch of ARC23_CHAPTERS) {
      if (!game.comicProgress23[ch.id]) return 'complete_arc23_chapter_' + ch.id;
    }
    return 'arc23_part1_complete_for_now';
  };

  window.markArc23ChapterRead = function(id){
    const so = window.arc23ObjectiveState();
    if (so !== ('complete_arc23_chapter_' + id)) return;
    game.comicProgress23 = game.comicProgress23 || {};
    game.comicProgress23[id] = true;
    // Matches every prior arc's own completion flag (arc21/arc22Complete)
    // — self-contained to this file, no aggregator dependency.
    if (id === 24) game.arc23Complete = true;
    const ch = ARC23_CHAPTERS.find(c => c.id === id);
    if (ch) {
      gainXP(ch.xp);
      toast('📖 ' + ch.title + ' — +' + ch.xp + ' Story XP', 3200);
    }
    if (ARC23_CHAPTER_SCENES[id]) {
      game.storyModalQueue = game.storyModalQueue || [];
      game.storyModalQueue.push({ title: ch.title, blurb: ARC23_CHAPTER_SCENES[id] });
    }
    if (typeof saveGameQuiet === 'function') saveGameQuiet();
    if (typeof updateUI === 'function') updateUI();
    if (typeof renderStory === 'function') renderStory();
    if (typeof window.showStoryModal === 'function' && game.storyModalQueue.length) {
      const next = game.storyModalQueue.shift();
      setTimeout(() => window.showStoryModal(next), 400);
    }
  };

  window.__ctShowArc23Splash = function(){
    const overlay = document.getElementById('arc23SplashOverlay');
    if (overlay) overlay.style.display = 'flex';
  };
  window.__ctCloseArc23Splash = function(){
    const overlay = document.getElementById('arc23SplashOverlay');
    if (overlay) overlay.style.display = 'none';
    game.arc23SplashSeen = true;
    if (typeof saveGameQuiet === 'function') saveGameQuiet();
  };

  const oldRenderStoryForArc23 = window.renderStory;
  window.renderStory = function(){
    if (oldRenderStoryForArc23) oldRenderStoryForArc23();
    const container = document.getElementById('storyContent');
    if (!container) return;
    const arc23Ready = window.arc23ObjectiveState() !== null;
    if (arc23Ready && !game.arc23SplashSeen && typeof window.__ctShowArc23Splash === 'function') {
      window.__ctShowArc23Splash();
    }
    let html = '<section class="story-act story-quest-panel"><div class="story-act-header">'+
      '<img src="assets/comics/arc23/arc23-cover-the-wider-tide.png" alt="Arc XXIII — The Wider Tide" style="width:100%;border-radius:8px;margin-bottom:12px;">'+
      '<div class="story-act-kicker">Arc XXIII</div><div class="story-act-title">The Wider Tide</div>'+
      '<div class="story-act-tagline">A home becomes important when people beyond its walls begin to depend on it.</div></div>';
    if (!arc23Ready) {
      html += '<div class="story-chapter locked"><div class="story-chapter-title">🔒 Arc XXIII Locked</div><div class="story-chapter-sub">'+
        (!game.arc22Complete ? 'Finish Arc XXII first.' : 'Reach Level 345 to begin.')+'</div></div></section>';
      container.insertAdjacentHTML('beforeend', html);
      return;
    }
    const so = window.arc23ObjectiveState();
    ARC23_CHAPTERS.forEach(function(ch){
      const done = !!(game.comicProgress23 && game.comicProgress23[ch.id]);
      const ready = !done && so===('complete_arc23_chapter_'+ch.id);
      const status = done?'✓ COMPLETE':(ready?'CURRENT':'🔒 LOCKED');
      let action;
      if (ready) {
        action = '<a class="btn btn-small" style="text-decoration:none;display:inline-block;" href="'+ch.image+'" target="_blank" rel="noopener">📖 Open Chapter (new tab)</a> '+
          '<button class="btn btn-small btn-success" onclick="markArc23ChapterRead('+ch.id+')">'+esc(ch.action || '✓ Mark Chapter Read')+'</button>';
      } else action = '<div class="story-chip">Follow the current Objective.</div>';
      html += '<article class="quest-item '+(done?'completed':(ready?'active':''))+'"><strong>Chapter '+ch.id+' — '+esc(ch.title)+'</strong><br>'+
        '<span style="font-size:.82rem;opacity:.82;">'+esc(ch.focus)+'</span><br>'+
        '<span style="font-size:.78rem;">'+status+'</span> <span style="font-size:.76rem;opacity:.75;">📖 Story XP: +'+ch.xp+'</span><div class="story-actions">'+action+'</div></article>';
    });
    if (so==='arc23_part1_complete_for_now'){
      html += '<div class="story-chapter" style="margin-top:8px;"><div class="story-chapter-sub">✓ All available Arc XXIII chapters read so far. More chapters are on the way — check back soon.</div></div>';
    }
    html += '</section>';
    container.insertAdjacentHTML('beforeend', html);
  };
})();
