(function(){
  // -------------------------------------------------------------------
  // ARC XXIV — THE PEOPLE WITHOUT NAMES. Gated at arc23Complete + level
  // 360, continuing the established +15-per-arc ladder (XXI:315,
  // XXII:330, XXIII:345, XXIV:360). Ch.24 sets game.arc24Complete = true,
  // matching every other arc's own finale flag.
  //
  // Core progression, per the outline this arc was built from: Arc
  // XVIII gave Fair Tide the Nameless QUESTION (Ch.22, "The Nameless
  // Question" — first sighting, purely observational, no name yet given
  // in-story beyond San and Joel's own private shorthand). Arc XXIII
  // re-planted quiet foreshadowing in its own Ch.21-24 ("Something
  // Watches"). Arc XXIV is the escalation: Fair Tide learns the Nameless
  // aren't an isolated curiosity but an organised, widespread network —
  // without ever confirming whether that network is hostile. San
  // deliberately does NOT coin the name "the Nameless" in this arc —
  // she already has it from Arc XVIII. Ch.14 is written specifically so
  // the captive confirms Fair Tide already has a word for them, rather
  // than supplying San with a brand-new one.
  //
  // Deliberately NOT resolved here, per the outline's own restraint:
  // who leads them, how many factions actually exist, and what they
  // ultimately want. N is not introduced — her eventual connection to
  // this network belongs much later (per the outline: Arc XXVII+ for
  // the network's internal complexity, Arcs XXVIII-XXX for N's personal
  // stake in it). Ch.22 and Ch.24 both plant a single deliberate note —
  // an operative shown helping rather than harming, without explanation
  // — establishing early that Nameless affiliation alone never tells
  // the player whether someone is good, bad, or something in between.
  // That ambiguity is load-bearing for the later N storyline and is not
  // an oversight to "fix" in a later pass.
  //
  // Same scope rule as every arc file since XVII: this file only wires
  // the story chapters. The gameplay additions Ch.6, 9, 18, and 20's own
  // notes call for (Verification Events, Warden Investigations, Council
  // security policy, and the permanent Fair Tide Intelligence system)
  // live in the separate scripts/arc24-mechanics.js, same split used for
  // Arc XXIII's own mechanics file. Per the outline's explicit "keep
  // Arc XXIV mechanically lighter than Arc XXIII" note, Fair Tide
  // Intelligence (Ch.20) is the only substantial addition — it's built
  // to explicitly read existing systems rather than introduce a new
  // resource screen, and to persist as permanent infrastructure well
  // past this arc, since the outline's own long-range roadmap has the
  // Nameless remaining active for many arcs to come.
  //
  // Ch.3 ("Aisyah's Records") is deliberately NOT given its own gameplay
  // panel — it's connective tissue explaining WHY Aisyah's records feed
  // Ch.20's Intelligence system later, not a standalone mechanic in its
  // own right. Same restraint Arc XXIII's own mechanics file used for
  // Ch.2's Fair Tide Requests (already covered elsewhere, nothing to add).
  //
  // XP escalates toward Ch.20 ("Watching the Watchers," the Fair Tide
  // Intelligence unlock and this arc's actual mechanical centerpiece) at
  // 400, with Ch.24's finale bump (380) kept below it — the same "one
  // centerpiece, not two" convention used for Arc XXIII's Ch.17/24 split.
  //
  // Cover image paths are placeholder guesses following the established
  // convention (chNN-slugified-title.png) — flagged for confirmation
  // like every chapter image before this, since no art exists yet to
  // confirm the real filenames against.
  // -------------------------------------------------------------------

  const ARC24_CHAPTERS = [
    {id:1, title:'The Question After the Question', focus:"After Arc XXIII's suspicious visitors, San goes back through the Harbour Office records and recognizes an old pattern — the Nameless, the ones Fair Tide brushed against once during the Horizon Engine dispute and never really understood. Fair Tide is much bigger now, and that changes what the pattern means.", image:'assets/comics/arc24/ch01-the-question-after-the-question.png', xp:260, action:'📖 Reopen the Old Question'},
    {id:2, title:'Nothing Stolen', focus:"Joy investigates the recent incidents and finds nothing stolen, sabotaged, or damaged. The visitors wanted routes, trade, leadership, security, access, and the Horizon Engine — information, not property. Joy finds that far more unsettling than an ordinary theft.", image:'assets/comics/arc24/ch02-nothing-stolen.png', xp:270, action:'🔍 Investigate the Incidents'},
    {id:3, title:"Aisyah's Records", focus:"Aisyah cross-checks Fair Tide's commercial records against the questionable visitors' claimed origins. None of the discrepancies are large on their own — a purchase, a route, a previous port that doesn't quite line up. Together, they form a pattern.", image:'assets/comics/arc24/ch03-aisyahs-records.png', xp:270, action:'📊 Cross-Reference the Ledgers'},
    {id:4, title:'Renn Finds the Pattern', focus:"Renn maps the visitors' movements against the Route Observatory's charts. Several people who supposedly have no connection to one another have all passed through the same obscure, out-of-the-way locations.", image:'assets/comics/arc24/ch04-renn-finds-the-pattern.png', xp:280, action:'🗺️ Map the Routes'},
    {id:5, title:'People Without Histories', focus:"Erynn searches every record Fair Tide can reach. The names exist. The people apparently exist. Their histories don't, not really. Mimi suggests they may be asking the wrong question — what if the names themselves are the least important thing about any of this?", image:'assets/comics/arc24/ch05-people-without-histories.png', xp:280, action:'❔ Question the Records'},
    {id:6, title:'The Missing Manifest', focus:"A ship departs normally. Afterward, the Harbour Office discovers one visitor entry has quietly vanished from its manifest — nothing broken into, nothing destroyed, just one person removed from the record as if they'd never been logged at all.", image:'assets/comics/arc24/ch06-the-missing-manifest.png', xp:280, action:'📄 Examine the Manifest'},
    {id:7, title:'What They Asked Caelan', focus:"Someone approaches Caelan with technical questions disguised as idle curiosity — not how the Horizon Engine works, but how often it's maintained, who has access, and when. Only afterward does Caelan realize the conversation was an inspection.", image:'assets/comics/arc24/ch07-what-they-asked-caelan.png', xp:280, action:'⚙️ Realize What Was Asked'},
    {id:8, title:"The Warden Doesn't Chase", focus:"Joy spots someone watching a restricted Fair Tide facility and, instead of arresting them on the spot, lets them walk away. San asks why. Joy: \"Because now we can see where they go.\"", image:'assets/comics/arc24/ch08-the-warden-doesnt-chase.png', xp:290, action:'👁️ Let Them Go'},
    {id:9, title:'Follow the Stranger', focus:"Senedra leads a quiet surveillance run while Joy coordinates from Fair Tide. The stranger meets no one directly — they leave something at a predetermined spot instead, collected later by someone else entirely.", image:'assets/comics/arc24/ch09-follow-the-stranger.png', xp:290, action:'🎯 Follow the Stranger'},
    {id:10, title:'No Signature', focus:"The recovered message carries no name, no crest, no captain, no settlement mark — only instructions. San recognizes the method. It's the same deliberate anonymity Fair Tide brushed against once before, years ago, and never resolved.", image:'assets/comics/arc24/ch10-no-signature.png', xp:300, action:'📜 Read the Message'},
    {id:11, title:'The Familiar Mark', focus:"Mimi recognizes a recurring, understated visual motif — one that's turned up before, including in material connected to Fair Tide's earlier brush with the Nameless. It may not be a formal emblem. It might simply be how they recognize one another.", image:'assets/comics/arc24/ch11-the-familiar-mark.png', xp:290, action:'🔎 Recognize the Mark'},
    {id:12, title:'They Were Here Before Us', focus:"Renn finds traces of the network that predate Fair Tide's rise entirely. The Nameless didn't form because of San, or because of the Horizon Engine. Fair Tide simply became interesting enough, eventually, for an existing network to start paying attention.", image:'assets/comics/arc24/ch12-they-were-here-before-us.png', xp:300, action:'🗂️ Trace the Older Records'},
    {id:13, title:'The First One We Hold', focus:"Joy's investigation finally gives Fair Tide enough grounds to detain a suspected operative — and they're strikingly ordinary. No dramatic weapons, no villain's speech, cooperative on small questions, and completely unwilling to identify who they actually work for.", image:'assets/comics/arc24/ch13-the-first-one-we-hold.png', xp:300, action:'🔒 Question the Captive'},
    {id:14, title:'A Name We Already Know', focus:'San says it plainly: "The Nameless." The stranger studies her rather than denying it. "You already have a word for us." They neither confirm nor deny it\'s what the organisation actually calls itself — Fair Tide simply keeps using the name it already had.', image:'assets/comics/arc24/ch14-a-name-we-already-know.png', xp:320, action:'🗣️ Say the Name'},
    {id:15, title:'Not a Prisoner', focus:"The operative hasn't stolen, sabotaged, or attacked anyone — nothing serious enough to justify holding them indefinitely. Some of the crew disagree, but San releases them anyway: Fair Tide can't claim to be neutral ground and then imprison people simply for refusing to explain themselves.", image:'assets/comics/arc24/ch15-not-a-prisoner.png', xp:300, action:'🕊️ Release Them'},
    {id:16, title:'The Engine', focus:"Renn and Erynn compare everything Fair Tide has gathered. The Nameless' strongest, most consistent interest isn't San, isn't Joel, isn't the pregnancy, and isn't Fair Tide's wealth. It's the Horizon Engine and the inter-world routes — specifically, access to them.", image:'assets/comics/arc24/ch16-the-engine.png', xp:300, action:'⚙️ Name the Real Interest'},
    {id:17, title:'Routes Are Power', focus:"Aisyah spells out what that access actually means — whoever understands the inter-world routes can shape trade, resources, information, and migration between settlements and worlds. Fair Tide has become strategically important almost entirely by accident.", image:'assets/comics/arc24/ch17-routes-are-power.png', xp:300, action:'💰 Weigh the Stakes'},
    {id:18, title:'Close the Doors?', focus:"Some push to restrict visitors, limit route information, and close sensitive facilities outright. San refuses to turn Fair Tide into a fortress just because something made it nervous — but she agrees that genuinely dangerous technology and route information deserve real, deliberate protection.", image:'assets/comics/arc24/ch18-close-the-doors.png', xp:310, action:'🚪 Decide the Balance'},
    {id:19, title:'Dinner Anyway', focus:"A deliberately ordinary chapter. The crew eats together, Soel causes his usual trouble, San and Joel get a quiet moment, and Fair Tide's night market carries on outside, the pregnancy present but understated. The Nameless don't get to consume everyone's life simply by existing.", image:'assets/comics/arc24/ch19-dinner-anyway.png', xp:300, action:'🍽️ Have Dinner Anyway'},
    {id:20, title:'Watching the Watchers', focus:"Fair Tide builds its own answer — not a spy guild, not paranoia, but its existing systems finally talking to each other. Harbour records, trade records, route observations, Warden reports, research, and divination start producing something new: an actual picture of what's been happening around Fair Tide all along.", image:'assets/comics/arc24/ch20-watching-the-watchers.png', xp:400, action:'🕸️ Watch the Watchers'},
    {id:21, title:'Another Nameless', focus:"A second suspected operative surfaces — different background, different appearance, an entirely different apparent profession, yet unmistakably the same underlying methods. The first one wasn't an isolated eccentric. This is a real network.", image:'assets/comics/arc24/ch21-another-nameless.png', xp:300, action:'👥 Meet the Second'},
    {id:22, title:'A Conversation Between Strangers', focus:"Rather than have Joy arrest this one, San meets them directly and asks what they actually want. The answer is thin, but one thing comes through clearly: Fair Tide isn't the only place they watch. Their network reaches much further than San assumed — and the conversation doesn't feel entirely hostile.", image:'assets/comics/arc24/ch22-a-conversation-between-strangers.png', xp:310, action:'💬 Ask Them Directly'},
    {id:23, title:'Someone Higher Up', focus:"Renn's accumulated route data shows real structure behind the individual operatives — reports moving somewhere, instructions coming back from somewhere. But Fair Tide still can't say who, or how many. N is deliberately not part of this yet; her stake in it belongs much later.", image:'assets/comics/arc24/ch23-someone-higher-up.png', xp:320, action:'🧭 Follow the Structure'},
    {id:24, title:'The People Without Names', focus:"The Crimson Tide sails again while Fair Tide keeps operating normally. Among the ordinary travelers is a face they've seen before — a wordless exchange with a stranger, a folded message passed on. Elsewhere, unseen hands lay Fair Tide's routes across a table, San filed only as \"CAPTAIN.\" And elsewhere still, another Nameless figure is shown quietly helping travelers through a dangerous route, for reasons nobody explains — a first, deliberate sign that this network is far more complicated than Fair Tide currently understands.", image:'assets/comics/arc24/ch24-the-people-without-names.png', xp:380, action:'🌊 Look at the Wider Network'}
  ];
  window.ARC24_CHAPTERS = ARC24_CHAPTERS;

  const ARC24_CHAPTER_SCENES = {
    1: "San goes back through the Harbour Office's own records the evening after Arc XXIII's stranger unease finally settles into something she can actually name.<br><br>Individually, none of the recent questions looked like much. Routes. Leadership. Defences. Trade agreements. Who has access to what, and when. Laid end to end on her own desk, though, they stop looking like curiosity and start looking like a survey.<br><br>She's seen this shape before. Years ago, during the Horizon Engine dispute, something watched the entire argument unfold without ever declaring an interest of its own — no demands, no attempt to control the routes, just watching. She and Joel never learned who they were. They just started calling them, between themselves, the Nameless, and then Fair Tide got busy enough that the question quietly stopped mattering.<br><br>\"It's them again,\" she says to Joel, not really a question.<br><br>\"Maybe they never left,\" he says. \"Maybe we just weren't big enough to watch closely before.\"<br><br>San doesn't answer right away. She's thinking about how much has changed since the last time this question came up — and how differently the same quiet attention reads on a Fair Tide this size.",
    2: "Joy works through the recent incidents methodically, the way she works through everything now, and comes back with a report that unsettles San more than a break-in would have.<br><br>Nothing stolen. Nothing sabotaged. Nobody hurt.<br><br>What the visitors actually wanted, laid out plainly: routes. Trade patterns. Who leads Fair Tide and how firmly. How security is organized. Who has access to the Horizon Engine, and under what conditions.<br><br>\"If they'd taken something, I'd know what to do about it,\" Joy says. \"This is harder. They didn't want anything we'd notice missing. They wanted to understand us.\"<br><br>San turns that over for a long moment. An ordinary thief wants something specific and leaves once they have it. This is something else — patient, thorough, and entirely uninterested in taking anything Fair Tide would think to guard.",
    3: "Aisyah spends two days buried in Fair Tide's own commercial records, matching the questionable visitors' claimed origins against what their purchases, cargo manifests, and prior ports actually say about them.<br><br>None of it is damning on its own. A trader who says they sailed from one settlement, but whose goods are priced like they came from somewhere else entirely. A captain whose stated route doesn't quite match the wear on their ship. Small things — the kind of discrepancy that means nothing in isolation.<br><br>\"Individually, I'd never have flagged any of these,\" Aisyah admits, spreading the ledgers across the table. \"Together, though — look. It's not random. Somebody's covering the same kind of gap, over and over.\"<br><br>San looks at the pattern Aisyah's laid out and feels the same unease from the Harbour Office records settle a little deeper.",
    4: "Renn takes what Aisyah found and layers it directly onto the Route Observatory's charts, tracing each visitor's actual movements against Fair Tide's growing map of the routes.<br><br>The pattern that comes back is stranger than either of them expects. Several of the people Aisyah flagged — people with no stated connection to one another, different professions, different home ports — have all passed through the same handful of obscure, barely-charted locations.<br><br>\"These aren't places anyone travels through by accident,\" Renn says, tapping the chart. \"Nobody stumbles into three of the same dead-end waypoints unless they're actually going somewhere specific.\"<br><br>\"So they know each other,\" San says.<br><br>\"Or they answer to the same thing,\" Renn says. \"Which might not be the same question.\"",
    5: "Erynn takes the names Aisyah and Renn have gathered and goes looking for whatever history ought to sit behind them — birth records, prior trade, family, anything that would make an ordinary person an ordinary person.<br><br>The names are there. The people, as far as anyone can prove, exist. But scratch past the surface and the histories thin out fast — vague enough to be true, specific enough to sound convincing, and somehow never quite enough to actually confirm.<br><br>\"It's like they were built to survive a glance,\" Erynn says, frustrated. \"Not a real look.\"<br><br>Mimi's been quiet through most of this, turning one of the names over in her head rather than on paper.<br><br>\"Maybe we're paying attention to the wrong thing,\" she says finally.<br><br>Renn looks at her. \"The names are the only thing we have.\"<br><br>\"What if that's the least important thing about any of them?\" Mimi asks.<br><br>Nobody has an answer for that yet. But from that point on, without anyone quite deciding it out loud, Renn keeps tracing routes, Erynn keeps chasing histories, and Mimi starts watching for the shape of things nobody else is looking at.",
    6: "The ship that leaves is unremarkable — routine cargo, routine paperwork, nothing about its departure that would draw a second look. It's only afterward, when a Harbour Office clerk goes back to close out the day's manifest, that something feels wrong.<br><br>One entry is gone. Not crossed out. Not amended. Simply absent, as if it had never been written in the first place.<br><br>Nobody broke into the Harbour Office. Nothing else on the page is disturbed. Whoever did this didn't need to force their way in at all — they needed one specific line to stop existing, and then they left everything else exactly as it was.<br><br>\"That's worse than theft,\" San says, staring at the gap where a name used to be. \"Theft, at least, you notice.\"<br><br>The Harbour Office starts double-checking its most sensitive entries from that point on — not because it expects this to happen constantly, but because it's just learned it can happen at all.",
    7: "Caelan doesn't think much of the conversation while it's happening. Someone stops by the Workshop, friendly enough, clearly impressed by the equipment, and asks a few questions any curious visitor might ask.<br><br>How often does this particular component need replacing? Who actually maintains it? Where does its power draw from? Who has access when the researchers aren't around?<br><br>It's only afterward, turning the exchange over while he cleans a tool he wasn't really using, that Caelan realizes none of those were the questions an admirer asks.<br><br>\"They weren't curious about my work,\" he tells San later, still faintly unsettled by his own conclusion. \"They were finding out how it fails, and who'd be standing there when it did.\"<br><br>San doesn't say anything for a moment. It's the second time this week something ordinary has turned out to be an inspection in disguise.",
    8: "Joy spots them from the Warden's Hall's own watch post — someone lingering a little too long near a restricted Fair Tide facility, closer than a wrong turn would explain.<br><br>She doesn't move on them. She just watches, and lets them leave on their own.<br><br>San, hearing about it afterward, is genuinely surprised. \"You let them go?\"<br><br>\"I know exactly where they were,\" Joy says. \"Arresting them tells me that, and nothing else. Letting them walk away tells me where they go next.\"<br><br>\"And?\"<br><br>\"Now I want to know where they're going,\" Joy says, already thinking three steps past the conversation.<br><br>It's a small moment, but it lands on San as something larger — Joy isn't reacting to trouble as it appears anymore. She's actually thinking like someone responsible for a whole settlement's safety, not just its next incident.",
    9: "Senedra takes point on the follow-up, quiet and unhurried the way she's always been best at, while Joy coordinates from Fair Tide and keeps the rest of the Warden's Hall clear of the operation.<br><br>The stranger doesn't meet anyone directly. That's the first thing Senedra notices — no contact, no conversation, nothing that would look suspicious to an ordinary onlooker. Instead they stop at an unremarkable spot, leave something behind without breaking stride, and keep walking.<br><br>Senedra stays with the item rather than the stranger. Sure enough, hours later, somebody else entirely arrives to collect it — someone who has clearly never met the first stranger in their life, at least not in any way that would draw attention.<br><br>\"They're not meeting,\" Senedra reports back. \"They're relaying.\"<br><br>Joy nods slowly, already thinking about how to build this kind of watching into something Fair Tide can actually repeat, rather than something that only works once by luck.",
    10: "Whatever was left at the drop point turns out to be a short, carefully worded message — instructions, nothing more, with no name attached to any of it.<br><br>No signature. No crest. No settlement mark. No captain's seal, no organization's stamp, nothing that would let Fair Tide trace it back to a single responsible party even if they wanted to.<br><br>San reads it twice, and recognizes the shape of it before she recognizes anything it actually says.<br><br>\"This is them,\" she says quietly. \"This is exactly how it felt back then — nobody willing to put their name to anything, on purpose, like it's a rule they all agreed to follow.\"<br><br>It's the first time since the Horizon Engine dispute that Fair Tide has held something this concrete in its hands. It still doesn't tell her who they are. It confirms, at least, that whoever they are, they haven't changed how they operate.",
    11: "Mimi finds it almost by accident — a small, understated design worked into the edge of the recovered message, easy enough to mistake for decoration if you weren't already looking for something.<br><br>She's seen it before. Not exactly the same, but close enough in shape and placement that it can't be coincidence — a fragment of it turns up in an old sketch from the Horizon Engine dispute, tucked into the corner of a report nobody thought twice about at the time.<br><br>\"It's not necessarily their emblem,\" she says, laying both images side by side. \"It might just be how they know each other. A recognition mark, not a banner.\"<br><br>Once she knows what she's looking for, Erynn and Renn both start finding smaller versions of it scattered through older Fair Tide records — never announced, never explained, just quietly present in the corners of things nobody examined closely enough before now.",
    12: "Renn's research takes an unexpected turn when a few of the older records reference activity that predates Fair Tide's founding entirely — faint, secondhand mentions of watchers, unnamed visitors, and messages without signatures, tucked into accounts of places San has never even sailed to.<br><br>\"This isn't new,\" Renn says, spreading the older documents out. \"Some of this is older than the Crimson Tide. Older than you, probably, as a captain.\"<br><br>San sits with that longer than she expects to need to. She'd assumed, without ever quite saying it out loud, that Fair Tide's growth was what had drawn the Nameless' attention in the first place — that she'd built something interesting enough to notice.<br><br>\"We didn't cause this,\" she says slowly. \"We just got big enough for something that was already out there to finally look our way.\"<br><br>It's a stranger thought than the alternative. It also, somehow, makes the world feel considerably larger than it did that morning.",
    13: "Joy's patient work finally pays off — a suspected operative, caught in the act of exactly the kind of quiet observation Fair Tide has been tracking for weeks, with enough evidence to justify actually holding them.<br><br>San half-expects, when she finally sees them, something dramatic. A disguise. A weapon built for exactly this situation. A speech.<br><br>Instead: an ordinary-looking person, calm, mildly inconvenienced, answering basic questions about themselves without much resistance at all. Where they're from. What they were doing near the facility. Simple things, given up easily.<br><br>The one thing they won't give up, no matter how the questioning turns, is who they actually work for.<br><br>\"You're very cooperative,\" San says eventually, unable to keep the observation to herself.<br><br>\"About most things,\" the stranger agrees, entirely unbothered.",
    14: 'San decides to stop circling the question and simply ask it directly.<br><br>"You have to have a name," she says. "An organization. Something."<br><br>The stranger studies her for a moment before answering, something almost amused behind it.<br><br>"The Nameless," San says, when no answer comes. "That\'s what we\'ve been calling you. For years, actually — longer than you might think."<br><br>"You already have a word for us," the stranger says. Not a question. Barely even a reaction.<br><br>"Is it wrong?"<br><br>A faint smile. "I didn\'t say that."<br><br>They give her nothing further — no confirmation that it\'s what the organisation calls itself, no denial either. San doesn\'t press it. Fair Tide already has the word it needs. It just took this conversation to realize the word had been sitting there, unconfirmed but unchallenged, the whole time.',
    15: "The debate over what to do with them doesn't take long, but it isn't comfortable.<br><br>They haven't stolen anything. Haven't sabotaged anything. Haven't hurt anyone. Whatever they were doing near that facility, it doesn't rise to the kind of offense that would justify holding someone indefinitely — and some of the crew say so plainly, uneasy at the idea of releasing someone they still don't trust.<br><br>San hears them out. Then she has the stranger released anyway.<br><br>\"Fair Tide doesn't get to call itself neutral ground,\" she says, mostly for the crew's benefit, \"and then lock someone up because they wouldn't explain themselves. That's not neutrality. That's just power with better manners.\"<br><br>The stranger leaves without ceremony, without gratitude, without a backward glance. Joy watches them go from the Warden's Hall's own vantage point, and keeps watching long after they're out of sight.",
    16: "Renn and Erynn sit down together with everything Fair Tide has actually gathered so far — every incident, every question, every recovered message — and look for what all of it actually points toward.<br><br>It isn't San, specifically. Plenty of the questions never touch her at all. It isn't Joel, and it certainly isn't the pregnancy, which nobody outside Fair Tide seems to know or care about. It isn't even Fair Tide's growing wealth, tempting as that explanation would be.<br><br>What keeps coming up, over and over, underneath every single incident: the Horizon Engine, and the inter-world routes it opens onto.<br><br>\"Not the Engine itself, even,\" Erynn says, tracing the pattern one more time to be sure. \"Access to it. Who controls it. Who can use it, and under what conditions.\"<br><br>San lets that settle. It's a narrower answer than she expected, and somehow a more unsettling one — this was never really about Fair Tide at all. Fair Tide just happens to be standing in front of the door.",
    17: "Aisyah doesn't need long to work out what that kind of interest actually means in practical terms.<br><br>\"Whoever understands the routes — really understands them, not just knows they exist — has leverage over everything that moves through them,\" she says, laying it out the way she'd explain any market to San. \"Trade. Resources people can't get anywhere else. Information nobody else has yet. Who gets to travel, and who doesn't. That's not a small thing to control. That's most things, eventually.\"<br><br>San sits with the scale of it. Fair Tide didn't set out to become strategically important to anyone beyond itself. It just happened to be the place that ended up understanding the routes better than almost anywhere else — and apparently, that alone was enough to make it worth someone's very patient attention.",
    18: "The proposal comes from a reasonable place, San has to admit — restrict who visits, tighten what route information gets shared, close off the facilities that seem to draw the most unwanted interest. Simple, defensible, and completely at odds with everything Fair Tide was built to be.<br><br>She says no to most of it.<br><br>\"We built this place so people could belong here,\" she tells the Council. \"I'm not turning it into a fortress because something out there made us nervous. That's not protecting Fair Tide. That's just letting them win a fight they haven't even started yet.\"<br><br>But she doesn't dismiss the concern outright either. Genuinely sensitive technology — the Horizon Engine chief among it — and the route information that matters most get real, deliberate protection: tighter access, better records, fewer casual exceptions. Fair Tide stays open. It just stops being careless about the handful of things actually worth guarding.",
    19: "Nothing happens in this one, on purpose.<br><br>The whole crew ends up around the same table for once, no expedition to plan and no crisis demanding anyone's attention. Someone complains, loudly and without much real conviction, that the food's gone cold before they got their share. Someone else steals a piece straight off another plate and refuses to apologize for it. Soel causes exactly the kind of trouble Soel always causes, and gets away with all of it, same as always.<br><br>San and Joel find a quiet minute in the middle of the noise — nothing dramatic, just his hand over hers for a moment, a shared look that doesn't need any words attached to it. The pregnancy sits there quietly in the background of the evening, present without needing to be the whole conversation.<br><br>Outside, Fair Tide's market keeps running the way it always does after dark, entirely unconcerned with anything the crew's been chasing all week.<br><br>The Nameless don't get a say in this evening. That's rather the point of it.",
    20: "Fair Tide's answer, when it finally comes together, isn't a new building or a new office or anyone's grand announcement. It's smaller than that, and more useful for being smaller.<br><br>The Harbour Office was already tracking visitors. Aisyah's records were already tracking trade. The Route Observatory was already tracking paths through the wider world. The Warden's Hall was already tracking incidents. Renn was already chasing patterns, Erynn was already chasing histories, Mimi was already watching for the shape of things nobody else noticed, Senedra was already watching the field. None of it was ever meant to talk to any of the rest of it.<br><br>\"We don't need a spy guild,\" San says, once the shape of the idea actually settles. \"We need everything we're already doing to actually talk to each other.\"<br><br>It isn't glamorous. It's mostly just paperwork learning to share a room. But the first time two unrelated reports land on the same desk and turn out to describe the same person, San understands exactly what she's just built — not a new system, but the connective tissue between six systems Fair Tide already had.",
    21: "The second one doesn't look anything like the first. Different build, different manner, a profession that, on paper, has absolutely nothing in common with the first operative's cover story.<br><br>But Joy clocks the pattern almost immediately — the same unhurried, uninterested-looking observation, the same careful refusal to take anything or damage anything, the same instinct to leave before a conversation could turn into a confrontation.<br><br>\"Same methods,\" Joy says, watching them go. \"Completely different person.\"<br><br>San lets that land properly. She'd half-hoped, without quite admitting it to herself, that the first operative had been some kind of isolated oddity — one strange visitor Fair Tide happened to catch. This confirms otherwise. Whatever the Nameless actually are, they're not one person, and they're not one kind of person either.",
    22: "This time San doesn't send Joy to make the arrest. She goes herself, plainly, and simply asks the question she actually wants answered.<br><br>\"What do you want from Fair Tide?\"<br><br>The operative doesn't give her much. A few careful non-answers, nothing San could repeat back to the Council as a real explanation. But one thing does come through, almost in passing, in a way that feels more honest than anything deliberately said.<br><br>\"Fair Tide isn't the only place we watch,\" they say.<br><br>San turns that over on the walk back. It should unsettle her more than it does. Somehow, oddly, the conversation didn't feel hostile at all — careful, evasive, entirely unwilling to explain itself, but not once did it feel like a threat. That contradiction sits with her longer than any of the concrete facts she's gathered so far.",
    23: "Renn lays out everything the Route Observatory has accumulated since this whole thread started, and the shape underneath it is unmistakable now: this was never a scattering of independent operatives, each doing as they pleased.<br><br>Reports move. Somewhere, they're received. Instructions come back out the other side. There's a structure here, deliberate and maintained, not chaos wearing a coordinated disguise.<br><br>What Renn can't do — what nobody at Fair Tide can currently do — is say who's actually receiving any of it. One leader. Several. Independent cells answering to something bigger than any of them individually. The data doesn't say, and guessing further than the data allows isn't really Renn's style.<br><br>\"We know there's a structure,\" Renn says. \"We don't know its shape yet.\"<br><br>San nods slowly, filing the uncertainty away rather than trying to force it into an answer it isn't ready to give. Some questions, she's learned, just take longer than others.",
    24: "The Crimson Tide is readied for another departure, same as always, while Fair Tide keeps running exactly the way it's learned to run without San standing over every piece of it.<br><br>Among the ordinary travelers filing out through the harbour gate is someone Fair Tide has seen before — nobody San would think to stop, nothing about them drawing a second look from anyone who isn't already watching for it. They pass another traveler on the road out. No greeting. No conversation. Just the smallest possible exchange — a folded message, passed hand to hand, gone before anyone nearby would even register it happened.<br><br>Elsewhere, in a room nobody at Fair Tide could point to on any chart, Fair Tide's own route diagrams are laid out across a table by hands San will never see. The Horizon Engine is marked. The Crimson Tide is marked. Somewhere on the newest report, San herself is identified by nothing more than a single word: CAPTAIN. The document is added to a collection that is, very clearly, already much larger than one report.<br><br>And elsewhere again, in a place just as unreachable, another figure wearing the same quiet anonymity is shown guiding a group of ordinary travelers safely through a genuinely dangerous route — no explanation offered, no allegiance declared, nothing to say whether this is the same network or a different face of it entirely.<br><br>Fair Tide had learned the names of thousands who crossed its harbour.<br><br>But some people had learned long ago that a name was something they could choose not to give."
  };
  window.ARC24_CHAPTER_SCENES = ARC24_CHAPTER_SCENES;

  window.arc24ObjectiveState = function(){
    if (!game.arc23Complete) return null;
    if (level() < 360) return null;
    game.comicProgress24 = game.comicProgress24 || {};
    for (const ch of ARC24_CHAPTERS) {
      if (!game.comicProgress24[ch.id]) return 'complete_arc24_chapter_' + ch.id;
    }
    return 'arc24_part1_complete_for_now';
  };

  window.markArc24ChapterRead = function(id){
    const so = window.arc24ObjectiveState();
    if (so !== ('complete_arc24_chapter_' + id)) return;
    game.comicProgress24 = game.comicProgress24 || {};
    game.comicProgress24[id] = true;
    // Matches every prior arc's own completion flag (arc22/arc23Complete)
    // — self-contained to this file, no aggregator dependency.
    if (id === 24) game.arc24Complete = true;
    const ch = ARC24_CHAPTERS.find(c => c.id === id);
    if (ch) {
      gainXP(ch.xp);
      toast('📖 ' + ch.title + ' — +' + ch.xp + ' Story XP', 3200);
    }
    if (ARC24_CHAPTER_SCENES[id]) {
      game.storyModalQueue = game.storyModalQueue || [];
      game.storyModalQueue.push({ title: ch.title, blurb: ARC24_CHAPTER_SCENES[id] });
    }
    if (typeof saveGameQuiet === 'function') saveGameQuiet();
    if (typeof updateUI === 'function') updateUI();
    if (typeof renderStory === 'function') renderStory();
    if (typeof window.showStoryModal === 'function' && game.storyModalQueue.length) {
      const next = game.storyModalQueue.shift();
      setTimeout(() => window.showStoryModal(next), 400);
    }
  };

  window.__ctShowArc24Splash = function(){
    const overlay = document.getElementById('arc24SplashOverlay');
    if (overlay) overlay.style.display = 'flex';
  };
  window.__ctCloseArc24Splash = function(){
    const overlay = document.getElementById('arc24SplashOverlay');
    if (overlay) overlay.style.display = 'none';
    game.arc24SplashSeen = true;
    if (typeof saveGameQuiet === 'function') saveGameQuiet();
  };

  const oldRenderStoryForArc24 = window.renderStory;
  window.renderStory = function(){
    if (oldRenderStoryForArc24) oldRenderStoryForArc24();
    const container = document.getElementById('storyContent');
    if (!container) return;
    const arc24Ready = window.arc24ObjectiveState() !== null;
    if (arc24Ready && !game.arc24SplashSeen && typeof window.__ctShowArc24Splash === 'function') {
      window.__ctShowArc24Splash();
    }
    let html = '<section class="story-act story-quest-panel"><div class="story-act-header">'+
      '<img src="assets/comics/arc24/arc24-cover-the-people-without-names.png" alt="Arc XXIV — The People Without Names" style="width:100%;border-radius:8px;margin-bottom:12px;">'+
      '<div class="story-act-kicker">Arc XXIV</div><div class="story-act-title">The People Without Names</div>'+
      '<div class="story-act-tagline">Not everyone who watches Fair Tide wants to be known.</div></div>';
    if (!arc24Ready) {
      html += '<div class="story-chapter locked"><div class="story-chapter-title">🔒 Arc XXIV Locked</div><div class="story-chapter-sub">'+
        (!game.arc23Complete ? 'Finish Arc XXIII first.' : 'Reach Level 360 to begin.')+'</div></div></section>';
      container.insertAdjacentHTML('beforeend', html);
      return;
    }
    const so = window.arc24ObjectiveState();
    ARC24_CHAPTERS.forEach(function(ch){
      const done = !!(game.comicProgress24 && game.comicProgress24[ch.id]);
      const ready = !done && so===('complete_arc24_chapter_'+ch.id);
      const status = done?'✓ COMPLETE':(ready?'CURRENT':'🔒 LOCKED');
      let action;
      if (ready) {
        action = 
          '<button class="btn btn-small btn-success" onclick="markArc24ChapterRead('+ch.id+')">'+esc(ch.action || '✓ Mark Chapter Read')+'</button>';
      } else action = '<div class="story-chip">Follow the current Objective.</div>';
      html += '<article class="quest-item '+(done?'completed':(ready?'active':''))+'"><strong>Chapter '+ch.id+' — '+esc(ch.title)+'</strong><br>'+
        '<span style="font-size:.82rem;opacity:.82;">'+esc(ch.focus)+'</span><br>'+
        '<span style="font-size:.78rem;">'+status+'</span> <span style="font-size:.76rem;opacity:.75;">📖 Story XP: +'+ch.xp+'</span><div class="story-actions">'+action+'</div></article>';
    });
    if (so==='arc24_part1_complete_for_now'){
      html += '<div class="story-chapter" style="margin-top:8px;"><div class="story-chapter-sub">✓ All available Arc XXIV chapters read so far. More chapters are on the way — check back soon.</div></div>';
    }
    html += '</section>';
    container.insertAdjacentHTML('beforeend', html);
  };
})();
