(function(){
  // -------------------------------------------------------------------
  // ARC XXXIII — THE FAMILY WE BECOME. Gated at arc32Complete + level
  // 495, continuing the established +15-per-arc ladder (XXX:450,
  // XXXI:465, XXXII:480, XXXIII:495). Ch.24 sets game.arc33Complete =
  // true, matching every other arc's own finale flag.
  //
  // Per the outline this arc was built from: Arc XXXII established
  // that life doesn't stop while San is pregnant. Arc XXXIII goes
  // further — San and Joel aren't merely preparing to have children;
  // everyone around them is discovering what place they'll have in
  // those children's lives. Joy becomes Ate Joy from several directions
  // at once (Joel's actual older sister and the twins' biological aunt,
  // AND increasingly San's own chosen sister — Ch.2/4's own joke about
  // San simply starting to call her Ate is the hinge the whole arc
  // turns on). Mama's memory (Ch.3, 17) gives San something she never
  // had before: proof that Joel's mother saw her as family, not simply
  // as her son's partner. Joy and Caelan become an established couple
  // (Ch.13) without being rushed toward marriage or children. Per the
  // outline's own explicit instruction, the twins remain unborn
  // throughout this arc — nothing here starts a birth countdown.
  //
  // Same scope rule as every arc file since XVII: this file only wires
  // the story chapters. The Family & Legacy gameplay system (Personal
  // Archive relationships, Family Infrastructure, Legacy Records) Ch.2,
  // 7, 10, 13, and 19's own notes call for lives in
  // scripts/arc33-mechanics.js, same split used since Arc XXIII.
  //
  // XP stays in a gentle, intimate range matching Arc XXXII's own
  // quieter pacing. Ch.17 ("Mama") is the centerpiece at 400 — the
  // chapter where San finally gets to know Mama's own side of their
  // relationship, which the outline calls out as the emotional core of
  // everything Ch.2-4's Ate joke was building toward. Ch.24's finale
  // keeps the "one centerpiece, not two" convention at 380, below the
  // centerpiece, and shares the arc's own title as always.
  //
  // Cover image paths are placeholder guesses following the established
  // convention (chNN-slugified-title.png) — flagged for confirmation
  // like every chapter image before this, since no art exists yet to
  // confirm the real filenames against.
  // -------------------------------------------------------------------

  const ARC33_CHAPTERS = [
    {id:1, title:'Their Room', focus:'San casually calls the new space "their room." Joel notices. Until now there have been supplies, plans and preparations — calling it their room makes the twins suddenly feel like two people who are actually coming home.', image:'assets/comics/arc33/ch01-their-room.png', xp:255, action:'🌅 Call It Their Room'},
    {id:2, title:'Ate', focus:'San says "Ate, can you pass me that?" to Joy without thinking. Joel notices too. There\'s no ceremony and no discussion about whether San is officially allowed to call her that — from then on, Ate simply starts becoming natural.', image:'assets/comics/arc33/ch02-ate.png', xp:270, action:'🌸 Say Ate'},
    {id:3, title:'What Mama Said', focus:"Joy tells San that hearing her say Ate reminds her of Mama before the storm — and that Mama used to talk about San, noticing how she treated her like a real mother, not merely Joel's. San knew how much Mama meant to her. She hadn't fully known what Mama thought of San.", image:'assets/comics/arc33/ch03-what-mama-said.png', xp:290, action:'🕯️ Hear What Mama Said'},
    {id:4, title:'Thought You Knew', focus:'San confronts Joel about never telling her his mother talked about her. "Thought you knew," he says. Joy remembers considerably more than Joel does. San realizes her place in Joel\'s family began forming long before Fair Tide existed.', image:'assets/comics/arc33/ch04-thought-you-knew.png', xp:280, action:'❤️ Realize You Thought She Knew'},
    {id:5, title:"We're a Team", focus:'San and Joel disagree over a practical preparation for the twins, and other people inevitably start giving advice. San stops listening to everyone else. "We\'re a team," she says. Pregnancy doesn\'t turn Joel into San\'s assistant — they\'re preparing to become parents together.', image:'assets/comics/arc33/ch05-were-a-team.png', xp:275, action:"🤰 Remember We're a Team"},
    {id:6, title:'Soel Was Here First', focus:"Soel discovers the babies' belongings and decides something intended for the twins now belongs to him. San points out they already have experience caring for one highly demanding small family member. Joel is unconvinced this counts as childcare experience.", image:'assets/comics/arc33/ch06-soel-was-here-first.png', xp:265, action:'🐈 Admit Soel Was Here First'},
    {id:7, title:'Ate Joy', focus:"Someone refers to Joy as the twins' future aunt — not chosen family this time, but Joel's actual older sister. Joy starts thinking about herself not merely as someone who'll help San and Joel, but as someone who'll have her own relationship with her niece and nephew.", image:'assets/comics/arc33/ch07-ate-joy.png', xp:285, action:'🧸 Recognize Ate Joy'},
    {id:8, title:'Her Little Brother', focus:'Everyone asks San how she\'s coping. Joy notices far fewer people ask Joel. "How are you?" she asks him. "Fine." "Try again." Joel eventually admits some of his uncertainty about becoming a father again under circumstances unlike anything he knew before. Joy doesn\'t fix it. She\'s simply his sister.', image:'assets/comics/arc33/ch08-her-little-brother.png', xp:280, action:'⚓ Be Her Little Brother'},
    {id:9, title:'Their Fair Tide', focus:"San and Joel realize their children won't grow up only inside their home — they'll grow up in Fair Tide. Ships, workshops, Horizon travelers, markets, the Archive, Soel, will simply be normal childhood scenery. To San, Veyren was once another world. To the twins, Veyren will be home.", image:'assets/comics/arc33/ch09-their-fair-tide.png', xp:285, action:'🏘️ Claim Their Fair Tide'},
    {id:10, title:'Caelan Notices a Problem', focus:'Caelan realizes Fair Tide has mostly been designed by adults thinking about adults — docks, workshops, stairs, storage, equipment. "They\'re going to be babies," Joy points out. "They won\'t stay babies," Caelan says, and begins considering changes that make Fair Tide safer for all its children.', image:'assets/comics/arc33/ch10-caelan-notices-a-problem.png', xp:290, action:'🔨 Watch Caelan Notice a Problem'},
    {id:11, title:"Someone Else's Child", focus:"A minor incident involving one of Fair Tide's existing children puts the issue into perspective. The child is fine, but the incident reminds everyone Fair Tide already has a next generation — San's twins won't be the beginning of it.", image:'assets/comics/arc33/ch11-someone-elses-child.png', xp:290, action:"🌊 Learn From Someone Else's Child"},
    {id:12, title:'The Family Table', focus:"A shared meal brings together people who would never have been one family on Earth — San's relatives, Joel and Ate Joy, Caelan, friends, crew, people Veyren brought together through circumstances none of them planned. San realizes the twins will grow up assuming this strange collection of relationships is perfectly ordinary. She likes that.", image:'assets/comics/arc33/ch12-the-family-table.png', xp:295, action:'🍲 Sit at the Family Table'},
    {id:13, title:'Joy and Caelan', focus:"Joy and Caelan's relationship has had enough time to develop naturally, and they finally acknowledge that what exists between them isn't casual anymore. No elaborate proposal, no sudden rush toward marriage — they simply choose to treat their relationship as established.", image:'assets/comics/arc33/ch13-joy-and-caelan.png', xp:300, action:'❤️ Recognize Joy and Caelan'},
    {id:14, title:'Stories From Before', focus:"The family shares stories about Earth — funny, embarrassing, painful, stories about Mama, about people the twins may never meet. San realizes her children will grow up hearing about a world they've never seen. Earth won't be their home. But it will still be part of their history.", image:'assets/comics/arc33/ch14-stories-from-before.png', xp:290, action:'📖 Tell Stories From Before'},
    {id:15, title:'The Family Archive', focus:"Renn asks why the Archive preserves worlds, rulers, magic and expeditions, but so little about ordinary people. The crew begins adding personal histories — where people came from, their families, who mattered to them. The Archive starts preserving not merely knowledge, but people.", image:'assets/comics/arc33/ch15-the-family-archive.png', xp:295, action:'📚 Build the Family Archive'},
    {id:16, title:'What They Inherit', focus:"Mimi reflects on what inheritance means in Veyren. The twins will inherit something unusual through San's Fountain-restored pregnancy — their eventual powers remain unknown. But inheritance isn't only magical or biological. They'll inherit stories, habits, relationships, Fair Tide's values.", image:'assets/comics/arc33/ch16-what-they-inherit.png', xp:290, action:'🌺 Consider What They Inherit'},
    {id:17, title:'Mama', focus:"San and Joy have a longer conversation about Mama — small things Joel wouldn't necessarily remember to mention, things Mama enjoyed about San, ordinary comments she made when San wasn't present. Nothing becomes a grand prophecy. That's precisely why it matters.", image:'assets/comics/arc33/ch17-mama.png', xp:400, action:'🌧️ Remember Mama'},
    {id:18, title:'What Remains', focus:"San thinks about the strange shape of family now. Mama isn't physically here. Others from Earth aren't here. The twins aren't replacements for anybody. Fair Tide isn't a replacement for Earth. One family doesn't erase another. Families grow around what remains.", image:'assets/comics/arc33/ch18-what-remains.png', xp:300, action:'🫶 Hold What Remains'},
    {id:19, title:'Built for Tomorrow', focus:"Caelan presents several practical improvements — safer residential walkways, better barriers around dangerous workspaces, family-friendly housing, protected community areas. San approves them for the settlement as a whole. She isn't redesigning Fair Tide for her children. She's recognizing Fair Tide is becoming somewhere families raise children.", image:'assets/comics/arc33/ch19-built-for-tomorrow.png', xp:310, action:'🛠️ Build for Tomorrow'},
    {id:20, title:"You Know I'll Be There", focus:'Joy and Joel share another quiet sibling moment. Joel doesn\'t need to formally ask whether his older sister will help with the twins. Still, Joy says it: "You know I\'ll be there." "I know." That\'s enough. Ate Joy already has her place.', image:'assets/comics/arc33/ch20-you-know-ill-be-there.png', xp:300, action:"🌸 Hear You Know I'll Be There"},
    {id:21, title:'Caelan at the Table', focus:'Caelan attends another family gathering, and San realizes nobody actually asked whether he was coming — of course he was. Caelan has quietly crossed the same invisible boundary San did with Joy. He isn\'t merely Joy\'s partner who visits anymore. He\'s becoming part of the family around her.', image:'assets/comics/arc33/ch21-caelan-at-the-table.png', xp:300, action:'🌿 Set a Place for Caelan at the Table'},
    {id:22, title:'Their Generation', focus:'Someone jokes that San and Joel\'s children might become explorers themselves one day. "Absolutely not," San objects immediately. Behind the joke lies something Fair Tide once couldn\'t afford to assume: there will be a next generation. They\'re building something they expect to outlive the present.', image:'assets/comics/arc33/ch22-their-generation.png', xp:300, action:'🌌 Consider Their Generation'},
    {id:23, title:'Before They Know Us', focus:'San and Joel sit together in the twins\' room. San wonders what their children will eventually think of them. Joel doesn\'t pretend to know. "We\'ll learn." "Together?" "Team." San smiles.', image:'assets/comics/arc33/ch23-before-they-know-us.png', xp:300, action:'🌙 Sit Before They Know Us'},
    {id:24, title:'The Family We Become', focus:'Fair Tide gathers for an ordinary evening — people connected by blood, by partnership, by people who became family simply because life kept placing them beside one another. San\'s hand rests over the twins. Joel\'s settles over hers. "Our family got big." "Yeah." The twins aren\'t here yet. Their family already is.', image:'assets/comics/arc33/ch24-the-family-we-become.png', xp:380, action:'🌅 Become The Family We Become'}
  ];
  window.ARC33_CHAPTERS = ARC33_CHAPTERS;

  const ARC33_CHAPTER_SCENES = {
    1: 'The room is still mostly supplies and half-finished plans — Caelan\'s measurements, a growing pile of things Joel has stopped questioning the necessity of, more blankets than any reasonable household needs.<br><br>San gestures at it, mid-conversation, entirely unplanned. "Their room," she says.<br><br>Joel looks at her.<br><br>"What?" San asks.<br><br>"Nothing," Joel says.<br><br>It isn\'t nothing, and they both know it. Until this exact moment, everything in that room has been preparation — supplies, plans, careful arrangements for a future still abstract enough to plan around. Calling it their room does something smaller and considerably larger at once. It stops being a project. It starts being where two people are actually coming home to.',
    2: 'It happens in the middle of something entirely mundane — San, Joy and Joel sorting through some errand none of them will later remember the details of — when San says, without any thought behind it at all, "Ate, can you pass me that?"<br><br>Joy passes it to her. Perfectly normal. No pause, no reaction.<br><br>A moment later, San actually hears what she said.<br><br>Joel noticed too.<br><br>"What?" San asks, already bracing.<br><br>"Nothing," Joel says, clearly amused.<br><br>"She\'s your Ate," San says, working through it out loud.<br><br>A pause.<br><br>"Now she\'s my Ate," San says, slower, like she\'s only just discovered this about herself.<br><br>Joy laughs outright. There\'s no ceremony to it, no formal discussion about whether San\'s actually allowed to call her that. Nobody needed to grant permission. From this exact, unplanned moment forward, Ate simply starts being true.',
    3: "Later, once the moment's had time to settle, Joy tells San something that catches her off guard entirely — hearing San say Ate reminds her, more than she expected, of Mama, before the storm.<br><br>San is surprised in a different direction than she expects to be. \"Mama talked about me?\" she asks.<br><br>\"Of course she did,\" Joy says, like this should be obvious.<br><br>What Joy remembers isn't one dramatic conversation. It's an accumulation — Mama noticing, more than once, how San treated her. Not merely as Joel's mother, someone to be polite to for his sake, but the way San might treat her own mother. Calling to check on her. Worrying about her. Actually listening when she talked, actually caring how she was doing.<br><br>Joy smiles, watching this land on San properly. \"She said you treated her like your real mother,\" she says. Then, unable to resist: \"Maybe even better sometimes.\"<br><br>\"Ate!\" San says, half-mortified.<br><br>It's funny, and San laughs along with it. But underneath the joke, it affects her considerably more than she expects. She knew, always, exactly how much Mama meant to her. She hadn't fully known, until this moment, what Mama thought of her in return.",
    4: 'San corners Joel with the discovery later that same day, still turning it over. "Did you know your mother talked about me?" she asks.<br><br>"Yeah," Joel says, entirely unbothered.<br><br>San waits for the rest of it. It doesn\'t come.<br><br>"And you never told me?" she presses.<br><br>"Thought you knew," Joel says, like this is a perfectly reasonable answer.<br><br>San stares at him. As it turns out, Joel genuinely remembers very little of the actual conversations — the substance slipped past him the way most things do when you\'re not the one it\'s really about. Joy, meanwhile, remembers considerably more, in considerably more detail, and appears entirely willing to share all of it.<br><br>"I\'m asking Ate from now on," San decides.<br><br>"Okay," Joel says, unbothered by his own demotion.<br><br>Underneath the comedy of it, something settles properly into place for San. Her place in Joel\'s family — in Mama\'s eyes specifically — began forming long before Fair Tide, long before any of this. She just hadn\'t known it until now.',
    5: 'The disagreement itself is small — some practical decision about how to prepare for the twins that San and Joel simply see differently. It wouldn\'t be worth mentioning at all, except that other people, predictably, start weighing in the moment they notice two people disagreeing about anything baby-related.<br><br>San eventually stops listening to any of them.<br><br>"We\'re a team," she tells Joel, cutting through everyone else\'s opinions at once.<br><br>"I know," Joel says, like this was never actually in question.<br><br>They work it out together, the two of them, without needing anyone else\'s input to get there. Pregnancy hasn\'t turned Joel into San\'s assistant, taking instructions and staying quiet. They\'re preparing to become parents together, as equals, the same way they\'ve done most things since Fair Tide began.',
    6: "Soel discovers the twins' belongings sometime during an otherwise unremarkable afternoon, and something intended specifically for the babies apparently now belongs to him, as far as he's concerned.<br><br>Joel removes him from it.<br><br>Soel returns to it almost immediately, entirely unbothered by having been removed once already.<br><br>San, watching the standoff unfold, points out that between the two of them, they already have real experience managing one extremely demanding small family member who refuses to listen to reason.<br><br>Joel is deeply unconvinced this counts as legitimate childcare experience.<br><br>Soel, for his part, finds the entire discussion beneath his notice and settles in regardless.",
    7: "Someone — San doesn't even remember who, later — refers to Joy in passing as the twins' future aunt, and something about hearing it said plainly lands differently than San calling her Ate ever has.<br><br>This isn't chosen family, not from Joel's side of it. Joy is their biological aunt. Joel's actual older sister, which makes her the twins' actual aunt, with nothing needing to be decided or granted about it at all.<br><br>What changes, watching Joy hear it said out loud, is how real the role suddenly feels to her. She isn't only thinking of herself anymore as someone who'll help San and Joel manage two newborns. She's starting to think of herself as someone who'll have her own relationship with her niece and nephew — entirely separate from her relationship with their parents, hers to build on her own terms.",
    8: '\'How are you holding up?\' San hears constantly these days, from nearly everyone she passes. Understandable, given the circumstances.<br><br>What Joy notices, watching the pattern from slightly outside it, is how rarely anyone thinks to ask Joel the same thing.<br><br>Fortunately, she knows her little brother well enough to ask anyway.<br><br>"How are you?" she asks him directly.<br><br>"Fine," Joel says.<br><br>Ate Joy has heard this particular answer from him more times than she can count over the years, and she isn\'t remotely fooled by it now. "Try again," she says.<br><br>Eventually, without much more prompting than that, Joel admits to some of what he\'s actually been sitting with — real uncertainty about becoming a father again, under circumstances unlike anything he\'s ever known or prepared for.<br><br>Joy doesn\'t try to fix any of it. She doesn\'t need to. She\'s simply his sister, listening, exactly the way she always has been.',
    9: "It occurs to San and Joel almost simultaneously, somewhere in an otherwise ordinary conversation: their children aren't only going to grow up inside their home. They're going to grow up in Fair Tide, in its entirety.<br><br>Ships coming and going. Workshops full of half-finished projects. Horizon travelers passing through with stories from worlds San still finds strange to imagine. Markets, the Archive, Soel getting into things he shouldn't, this enormous accumulated collection of people who somehow became family — all of it, simply normal childhood scenery to two children who'll never know any different.<br><br>San remembers, distinctly, what it felt like the first time Veyren was another world entirely, impossible and disorienting.<br><br>To the twins, it will simply be home. San isn't sure whether that thought comforts her or unsettles her slightly. Possibly both, at once.",
    10: 'Caelan walks Fair Tide the way he walks everything, and this time what he notices is how thoroughly the whole settlement has been built by adults, for adults, without anyone particularly meaning to exclude children from the design of it. Docks with drops nobody bothered to guard against. Workshops full of equipment built for adult hands. Stairs, storage areas, entire sections of the settlement that assume everyone moving through them is already grown.<br><br>"They\'re going to be babies," Joy points out, watching him survey it all.<br><br>"They won\'t stay babies," Caelan says, already moving past the observation toward the actual problem.<br><br>He begins considering changes — modest ones, nothing dramatic — that would make Fair Tide meaningfully safer for all of its children, not merely the two San and Joel are expecting.',
    11: "The incident itself is minor, in the end — one of Fair Tide's existing children wanders somewhere they shouldn't have, gets caught out by changing weather, ends up briefly separated from their family before anyone quite realizes it's happened.<br><br>Joy coordinates the response without hesitation. Caelan's own thorough knowledge of the settlement's actual layout helps track down exactly where the child likely went.<br><br>The child turns out to be entirely fine — cold, a little frightened, otherwise unharmed.<br><br>But the whole thing lands on everyone differently than it might have a few arcs ago. Fair Tide already has a next generation, quietly growing up around them this entire time. San's twins, whenever they arrive, won't be the beginning of that. They'll simply be joining something that's already well underway.",
    12: "The shared meal brings together, without anyone particularly planning it that way, a collection of people who would never have shared a single table if any of them were still on Earth. San's own relatives. Joel, and Ate Joy beside him. Caelan, increasingly a fixture rather than a guest. Friends who started as strangers. Crew who started as coworkers. People Veyren simply put in each other's path, for reasons none of them chose, until somehow this is what family looks like now.<br><br>San watches all of it happening across one crowded table and realizes, with something close to certainty, that the twins will grow up assuming this strange, sprawling collection of relationships is perfectly ordinary — because to them, it always will have been.<br><br>She finds, turning the thought over, that she genuinely likes that.",
    13: "Joy and Caelan's relationship has had, by now, considerably more time to settle into itself than either of them probably expected when it started. What finally changes isn't a single dramatic moment. It's an acknowledgment, quiet and almost anticlimactic in how little ceremony it needs: whatever exists between them stopped being casual a while ago, and it's time they both simply said so.<br><br>There's no elaborate proposal. No sudden rush toward marriage, or any of the milestones people might expect to follow. They simply choose, together, to treat what they have as established — real, ongoing, worth building around rather than merely enjoying as it comes.<br><br>For Caelan, this also means something else, somewhat to his own visible resignation: growing steadily more entangled with the sprawling, enormous extended family that comes attached to Joy. He appears to accept his fate without much of a fight.",
    14: "The stories come out slowly, over the course of an evening nobody planned around storytelling specifically. Funny ones first — embarrassing childhood moments, old arguments that seem ridiculous in hindsight. Then, gradually, softer ones. Painful ones. Stories about Mama. Stories about people from Earth the twins, San realizes somewhere in the middle of it, may simply never meet.<br><br>It settles on her slowly, listening to all of it accumulate. Her children are going to grow up hearing about an entire world they'll never actually see for themselves — Earth, with all its specific, ordinary, sometimes painful details, existing for them only as stories told at a table on a completely different planet.<br><br>Earth won't be their home. It never will be. But listening to the stories keep coming, San understands it'll still be part of their history regardless — carried forward the only way it still can be.",
    15: 'Renn asks the question almost offhandedly, the way his best questions tend to arrive. Why does the Archive preserve worlds, and rulers, and magic, and entire expeditions in painstaking detail — while ordinary people, the ones who actually lived through all of it, get so little space by comparison?<br><br>Nobody has a satisfying answer.<br><br>So the crew starts fixing it themselves. Where people actually came from. What their families looked like, however unconventional. Who mattered to them, and why. What they still remember, on the days they let themselves think about it.<br><br>The Archive starts becoming something slightly different than it\'s been until now — not merely a record of what Fair Tide has learned about Veyren\'s worlds and dangers, but a record of who actually built this place, one ordinary life at a time.',
    16: "Mimi turns the question over out loud one evening, half to herself: what does inheritance even mean, here, in Veyren, for two children conceived the way San and Joel's were?<br><br>The twins will inherit something genuinely unusual, tied to the Fountain's own restoration of San's pregnancy — what that eventually means for them, what abilities or nature they might carry, remains entirely unknown even to Mimi, who understands more about it than almost anyone.<br><br>But inheritance was never only magical, or only biological, Mimi points out, and the more she says it the more obviously true it becomes. The twins will inherit stories, the ones already being told around them. Habits, absorbed simply from watching. Relationships, already waiting for them before they're even born. Fair Tide's own values, lived rather than taught. All of it, quietly accumulating, long before either child takes a single breath of their own.",
    17: "San and Joy end up talking about Mama longer than either of them plans to, the conversation drifting somewhere neither quite steers it.<br><br>Joy has details Joel simply never thought to mention — not because he was hiding anything, just because some things don't occur to him as worth repeating. Small things. What Mama genuinely enjoyed about San's company. Things she'd bring up again days later, clearly still turning them over. Ordinary, offhand comments she made about San when San herself wasn't even in the room to hear them.<br><br>None of it becomes some grand revelation — no sign that Mama somehow foresaw San and Joel's entire future together, nothing that dramatic. That's precisely why it matters as much as it does. These are simply memories of a mother who recognized, plainly and without needing to make a point of it, that the woman her son loved genuinely cared about her too.<br><br>San leaves the conversation with a little more of Mama's own side of things than she's ever had before. It isn't closure, exactly. It's something quieter, and in its own way considerably more valuable.",
    18: "San sits with the strange, layered shape of family as it exists now, turning it over slowly rather than trying to resolve it into something simpler.<br><br>Mama isn't physically here, and never will be again. Others from Earth aren't here either — an entire life's worth of people San still carries with her, none of them within reach anymore. She and Joel both already hold memories of children and family from lives they lived before any of this.<br><br>The twins, whenever they arrive, aren't replacements for anyone. They were never going to be. Fair Tide isn't a replacement for Earth, either, however much of a home it's become.<br><br>One family, San realizes, doesn't erase another simply by existing alongside it. Families grow around whatever remains — layered, overlapping, none of it canceling out what came before.",
    19: "Caelan lays out several practical improvements at once, having clearly been thinking about this longer than one conversation's worth — safer walkways through the residential quarter, better barriers around the workspaces that were never built with small children in mind, housing considerations that actually account for families rather than assuming everyone living there is a single adult, protected community spaces where children can simply exist without needing constant supervision.<br><br>San approves all of it, for the settlement as a whole, without hesitating.<br><br>She isn't redesigning Fair Tide around her own children specifically, and she's careful, even to herself, not to let it become that. She's recognizing something larger and considerably more accurate: Fair Tide is becoming somewhere families actually expect to raise children, plural, indefinitely — not just hers.",
    20: 'Joy and Joel end up with another one of their quiet moments, the kind that doesn\'t need much said to mean something. Joel has never actually needed to formally ask his older sister whether she\'ll help with the twins once they arrive. It was never really a question between them.<br><br>Joy says it anyway, plainly, because some things are still worth saying out loud even when they\'re already understood. "You know I\'ll be there," she tells him.<br><br>"I know," Joel says.<br><br>That\'s the whole conversation, really. It doesn\'t need to be longer than that. Ate Joy already has her place in all of this, and has for a while now — this is simply the moment it gets said plainly between the two people it was always actually about.',
    21: 'Caelan turns up to another family gathering, exactly as he has for a while now, and it\'s only partway through the evening that San notices something: nobody actually asked him whether he was coming this time. Of course he was coming. It stopped being a question at some point without anyone deciding when.<br><br>San glances at Joy, unable to help herself.<br><br>Joy notices immediately. "Don\'t," she says.<br><br>"I didn\'t say anything," San says.<br><br>"Your face did," Joy says.<br><br>It\'s funny, and they both know it. But underneath the joke, San recognizes exactly what\'s happening, because she\'s lived through the same quiet shift herself. Caelan has crossed the same invisible boundary San did with Joy, without any formal moment marking it. He isn\'t merely Joy\'s partner who happens to visit anymore. He\'s becoming part of the family that\'s grown up around her.',
    22: 'Someone at the Horizon workshop makes an offhand joke — one day, San and Joel\'s children might grow up to be explorers themselves, out mapping whatever\'s still beyond the routes Fair Tide already knows.<br><br>"Absolutely not," San says, immediately and with total conviction.<br><br>Joel glances at her, clearly fighting a smile. "They\'re not born yet," he points out.<br><br>"Exactly," San says. "Too young."<br><br>It\'s a joke, and everyone laughs, San included eventually. But underneath it sits something Fair Tide genuinely couldn\'t have assumed, not so long ago — that there will be a next generation at all, growing up here, inheriting whatever they end up building. They\'re not simply surviving long enough to see tomorrow anymore. They\'re building something they fully expect to outlive the present entirely.',
    23: 'San and Joel end up sitting together in the twins\' half-finished room, neither of them saying much at first.<br><br>San finally voices something that\'s been sitting with her for a while. What will their children eventually think of them? Will they turn out to actually be good at this? Will they understand two people whose own lives began under such entirely different rules than the ones their children will grow up inside?<br><br>Joel doesn\'t pretend to have an answer ready. "We\'ll learn," he says, simply.<br><br>San looks at him. "Together?" she asks, though she already knows.<br><br>Joel looks almost confused that she needed to ask at all. "Team," he says, like it was never in question.<br><br>San smiles, and lets that be enough.',
    24: 'Fair Tide gathers for an entirely ordinary evening — nothing planned, nothing marking the occasion beyond people simply choosing to be near each other. Aisyah and the wider family settle in together. Ate Joy sits close beside Caelan. Crew drift in and out through the evening, the way they always do. Soel occupies somewhere thoroughly inconvenient, as always.<br><br>There are people here connected by blood. People connected through partnership, chosen rather than given. People who became family simply because life kept placing them beside one another, over and over, until nobody quite remembers when the distinction stopped mattering.<br><br>San looks at Joy. Ate. She thinks of Mama, and everything Joy\'s given her of her these past weeks. She thinks of the family she came from, the family Joel came from, the people they both still carry from Earth, and the enormous, sprawling family their children are about to inherit before they\'ve even arrived to claim it.<br><br>Her hand rests over the twins. Joel\'s hand settles over hers.<br><br>"Our family got big," San says.<br><br>Joel looks around at all of it. "Yeah," he says.<br><br>San considers him for a moment. "Your fault," she decides.<br><br>"How?" Joel asks, entirely reasonably.<br><br>San laughs. She has absolutely no argument ready, and doesn\'t particularly need one.<br><br>Around them, Fair Tide carries on exactly as it always has. The twins aren\'t here yet.<br><br>Their family already is.'
  };
  window.ARC33_CHAPTER_SCENES = ARC33_CHAPTER_SCENES;

  window.arc33ObjectiveState = function(){
    if (!game.arc32Complete) return null;
    if (level() < 495) return null;
    game.comicProgress33 = game.comicProgress33 || {};
    for (const ch of ARC33_CHAPTERS) {
      if (!game.comicProgress33[ch.id]) return 'complete_arc33_chapter_' + ch.id;
    }
    return 'arc33_part1_complete_for_now';
  };

  window.markArc33ChapterRead = function(id){
    const so = window.arc33ObjectiveState();
    if (so !== ('complete_arc33_chapter_' + id)) return;
    game.comicProgress33 = game.comicProgress33 || {};
    game.comicProgress33[id] = true;
    // Matches every prior arc's own completion flag (arc31/arc32Complete)
    // — self-contained to this file, no aggregator dependency.
    if (id === 24) game.arc33Complete = true;
    const ch = ARC33_CHAPTERS.find(c => c.id === id);
    if (ch) {
      gainXP(ch.xp);
      toast('📖 ' + ch.title + ' — +' + ch.xp + ' Story XP', 3200);
    }
    if (ARC33_CHAPTER_SCENES[id]) {
      game.storyModalQueue = game.storyModalQueue || [];
      game.storyModalQueue.push({ title: ch.title, blurb: ARC33_CHAPTER_SCENES[id] });
    }
    if (typeof saveGameQuiet === 'function') saveGameQuiet();
    if (typeof updateUI === 'function') updateUI();
    if (typeof renderStory === 'function') renderStory();
    if (typeof window.showStoryModal === 'function' && game.storyModalQueue.length) {
      const next = game.storyModalQueue.shift();
      setTimeout(() => window.showStoryModal(next), 400);
    }
  };

  window.__ctShowArc33Splash = function(){
    const overlay = document.getElementById('arc33SplashOverlay');
    if (overlay) overlay.style.display = 'flex';
  };
  window.__ctCloseArc33Splash = function(){
    const overlay = document.getElementById('arc33SplashOverlay');
    if (overlay) overlay.style.display = 'none';
    game.arc33SplashSeen = true;
    if (typeof saveGameQuiet === 'function') saveGameQuiet();
  };

  const oldRenderStoryForArc33 = window.renderStory;
  window.renderStory = function(){
    if (oldRenderStoryForArc33) oldRenderStoryForArc33();
    const container = document.getElementById('storyContent');
    if (!container) return;
    const arc33Ready = window.arc33ObjectiveState() !== null;
    if (arc33Ready && !game.arc33SplashSeen && typeof window.__ctShowArc33Splash === 'function') {
      window.__ctShowArc33Splash();
    }
    let html = '<section class="story-act story-quest-panel"><div class="story-act-header">'+
      '<img src="assets/comics/arc33/arc33-cover-the-family-we-become.png" alt="Arc XXXIII — The Family We Become" style="width:100%;border-radius:8px;margin-bottom:12px;">'+
      '<div class="story-act-kicker">Arc XXXIII</div><div class="story-act-title">The Family We Become</div>'+
      '<div class="story-act-tagline">Family isn\'t just who you were born with.</div></div>';
    if (!arc33Ready) {
      html += '<div class="story-chapter locked"><div class="story-chapter-title">🔒 Arc XXXIII Locked</div><div class="story-chapter-sub">'+
        (!game.arc32Complete ? 'Finish Arc XXXII first.' : 'Reach Level 495 to begin.')+'</div></div></section>';
      container.insertAdjacentHTML('beforeend', html);
      return;
    }
    const so = window.arc33ObjectiveState();
    ARC33_CHAPTERS.forEach(function(ch){
      const done = !!(game.comicProgress33 && game.comicProgress33[ch.id]);
      const ready = !done && so===('complete_arc33_chapter_'+ch.id);
      const status = done?'✓ COMPLETE':(ready?'CURRENT':'🔒 LOCKED');
      let action;
      if (ready) {
        action = 
          '<button class="btn btn-small btn-success" onclick="markArc33ChapterRead('+ch.id+')">'+esc(ch.action || '✓ Mark Chapter Read')+'</button>';
      } else action = '<div class="story-chip">Follow the current Objective.</div>';
      html += '<article class="quest-item '+(done?'completed':(ready?'active':''))+'"><strong>Chapter '+ch.id+' — '+esc(ch.title)+'</strong><br>'+
        '<span style="font-size:.82rem;opacity:.82;">'+esc(ch.focus)+'</span><br>'+
        '<span style="font-size:.78rem;">'+status+'</span> <span style="font-size:.76rem;opacity:.75;">📖 Story XP: +'+ch.xp+'</span><div class="story-actions">'+action+'</div></article>';
    });
    if (so==='arc33_part1_complete_for_now'){
      html += '<div class="story-chapter" style="margin-top:8px;"><div class="story-chapter-sub">✓ All available Arc XXXIII chapters read so far. More chapters are on the way — check back soon.</div></div>';
    }
    html += '</section>';
    container.insertAdjacentHTML('beforeend', html);
  };
})();
